%%% This file was automatically generated by snmpc_mib_to_hrl version 5.3
%%% Date: 13-May-2019::21:35:12
-ifndef('OTP-TC').
-define('OTP-TC', true).

%% Oids

-define(otpTcModule, [1,3,6,1,4,1,193,19,1,1,2]).


%% Range values


%% Default values

-endif.
