// RaconH English Translation Hook v86
(function(){
var _m={
// --- Treasure hunt description (MUST be first: 绝学/银币/品质/次/万 components fire early) ---
'每次寻宝获得3万银币，同时必得绝学心法\n寻宝10次必得紫色品质以上绝学心法':
    'Each hunt: 30,000 Silver + guaranteed Skill Book\n10x hunt: guaranteed Purple-quality or above Skill Book',
'每次寻宝获得3万银币，同时必得绝学心法':
    'Each hunt: 30,000 Silver + guaranteed Skill Book',
'寻宝10次必得紫色品质以上绝学心法':
    '10x hunt: guaranteed Purple-quality or above Skill Book',
// --- First recharge panel (must precede 充值→Recharge component) ---
'立即充值':'Top Up Now',
'首充豪礼':'First Recharge Gift',
'首充奖励至少充值':'Need recharge ',
'元可领':' Yuan to claim',
// --- VIP / Privilege card (compound forms before component words) ---
'黄金特权卡':'Gold Privilege Card',
'黄金特权':'Gold Privilege',
'特权卡效果可叠加':'(Effects can stack)',
'元宝狂送':'Gem Giveaway',
'首次赠送':'First gift: ',
'每天可领取':'Daily: ',
'尊贵黄金特权称号':'Prestigious Gold Privilege Title',
'战力飙升':'Power Boost ',
'战力直升':'Power Boost +',
'特权称号':'Privilege Title',
'特权':'Privileges',
'属性加成':'Stat Bonus',
'墨宠属性':'Pet Stats ',
'转生属性':'Rebirth Stats ',
'成长加速':'Growth Boost',
'挂机经验':'AFK EXP ',
'挂机金币':'AFK Gold ',
'挂机':'AFK ',
'永久生效':'Permanent',
'半月投':'Bi-Monthly',
'等级投':'Level Pass',
'钻石':'Diamond','黄金':'Gold','尊贵':'Noble ',
// --- Chat system UI ---
'系统频道禁止发言':'System channel — muted',
'聊天发送信息输入区域':'Type a message...',
// --- Enhance screen ---
'所需材料':'Required Materials',
// --- Mail system ---
'未领取的邮件系统默认为您保存15天，请注意查收！':'Unclaimed mail is kept for 15 days — claim before it expires!',
'邮件内容':'Mail Content',
'立即领取':'Claim Now',
'邮箱':'Mailbox','战书':'War Notice','未读':'Unread',
'每日结算':'Daily Settlement','结算奖励':'Settlement Reward',
'一键领取':'Claim All',
// --- System announcements (substrings after {0} substitution) ---
// NOTE: template uses 战力榜 (not Power榜); 战力→Power runs LATER so key must use original
'叱咤风云，笑傲江湖。战力榜第一名':'Power Rank #1 ',
'回到了龙门客栈，势必再掀起一场腥风血雨':' has returned to Dragon Gate Inn!',
'[系统]':'[System]','[系统提示]':'[System]',
// --- Login / Server ---
'账号':'Account','密码':'Password',
'选择区服':'Select Server','点击换服':'Switch Server',
'切换区服':'Switch Server','区服':'Server','充值':'Recharge',
// --- Dungeon unlock conditions ---
'到达剧情副本第':'Reach Story Ch.','关后开启':'to unlock',
// --- Feature names ---
'门派成员':'Guild Members','职位':'Role',
'转生命轮':'Rebirth Wheel',
// --- Skill panel labels (compound forms before 绝学→Skills) ---
'绝学境界':'Skill Realm','绝学属性':'Skill Stats','激活条件':'Requirements','额外属性':'Extra Stats',
'境界':'Realm',
'命轮':'Fate Wheel','墨宠':'Pet','命格':'Destiny','绝学':'Skills','聚宝蟾':'Treasure','等级礼':'Lv.Gift',
'七日礼':'7-Day Gift','自动任务':'Auto Task','自动':'Auto ','日常任务':'Daily Quest','盟会正殿':'Guild Hall','盟会职位':'Guild Rank',
'盟会试炼':'Guild Trial','冲榜竞技':'PvP Rank','充值活动':'Top-up Event',
'装扮':'Costume','称号':'Title','论剑台':'Duel Arena','神兵':'Weapon','摆摊':'Market',
'魔神入侵':'Devil Raid','好友系统':'Friends','神器':'Artifact','功能预告':'Preview',
// --- Skill book names (juexue_data) ---
'龙爪功':'Dragon Claw Art',
'罗汉伏魔功':'Luohan Devil Fist','圣火令神功':'Sacred Flame Art','大金刚掌':'Great Vajra Palm',
'神门十三剑':'Thirteen Gate Swords','大九天手':'Nine Heavens Hand','空明拳':'Void Clarity Fist',
'乾坤大挪移':'Universe Transfer','九阴真经':'Nine Yin Classic','七伤拳':'Seven Injury Fist',
'纯阳无极功':'Pure Yang Art','混元功':'Primal Unity Art','碧波掌法':'Blue Wave Palm',
'凌波微步':'Rippling Steps','玉萧剑法':'Jade Flute Sword','太极拳剑':'Tai Chi Sword',
'两仪剑法':'Yin-Yang Sword','绕指柔剑':'Supple Sword','易筋经':'Muscle Classic','伏虎拳':'Tiger Fist',
// --- Active skill names (skill_data) ---
'凌霄剑法':'Soaring Sword Art','狂风快剑':'Gale Sword','雷霆万钧':'Thunder Strike',
'碧海潮生':'Ocean Surge','凌烟剑法':'Misty Sword Art','落英神剑':'Petal Sword',
'万剑归宗':'Myriad Swords','北冥神功':'North Sea Art',
'无视冷却':'Ignore CD','附加冰冻':'Freeze','附加中毒':'Poison',
'无视防御':'Ignore DEF','必定暴击':'Guaranteed Crit','闪避反伤':'Dodge Counter',
'附加沉默':'Silence','附加眩晕':'Stun',
// --- Item descriptions ---
'霸气墨宠':'Mighty Pet','输出暴涨':'DMG Surge ','暴涨':'Surge ',
'最强群攻':'Max AOE','全屏大招':'Full AOE','杀怪效率提升':'Kill EFF+','杀怪效率+':'Kill EFF+',
'极品武器':'Premium Weapon','绝世武学':'Supreme Arts','龙战八荒':'Dragon Realm',
'卓越':'Superior','箱':' Box','银票':'Silver Ticket','9折':'10% Off',
// --- Boss drop log ---
'记录击败首领Drop的珍稀道具、Equip':'Records of rare items & equipment dropped by bosses',
'珍稀道具':'Rare Items','珍稀':'Rare','首领':'Boss','击败':'Defeated',
'道具':'Item','记录':'Records',
'、':', ',
// --- Item tooltip ---
'激活或提升':'Activate or upgrade ','类型：':'Type: ','通用':'Universal',
// --- Treasure hunt UI ---
'积分：':'Points: ','积分不足':'Insufficient points','寻宝记录':'Hunt Records','积分':'Points',
// --- Common UI labels ---
'提示':'Notice','立即使用':'Use Now',
'盟会战力':'Pwr:','战斗力':'Combat Power','战力：':'Power: ','战力:':'Power:','战力':'Power',
'恭喜{0}击杀{1}，获得珍贵物品：{2}！':'Congrats! {0} defeated {1}, got: {2}!',
'未知错误':'Unknown error','背包或仓库为空':'Bag/storage empty','空间不足':'No space',
'位置已被占用':'Slot occupied','不可穿戴装备':'Cannot equip','已穿戴':'Equipped',
'绑定元宝不足':'Insufficient bound gems','物品数量错误':'Invalid qty',
'此技能不能升级':'Skill cannot level up','技能组CD冷却中':'Skill group CD',
'您当前还未进入场景':'Not in scene yet','系统出错，请稍候再试':'System error. Retry.',
'创建角色失败':'Create char failed','背包空间不足':'Bag full','物品使用玩家等级不够':'Level too low',
'物品不能使用':'Cannot use','仓库已满':'Storage full','装备等级不能高于角色等级':'Gear lvl > char lvl',
'铸魂失败':'Soul Cast failed','铸魂等级已满':'Soul Cast max',
'铸魂配置出错，请联系GM更新配置！':'Soul Cast config error. Contact GM.',
'强化成功':'Enhanced!','功能未开启':'Feature locked',
'组队等级不足！':'Party lvl too low!','已有队伍！':'Already in party!',
'创建队伍失败！':'Create party failed!','队伍不存在！':'Party not found!',
'您不是队长！':'Not the leader!','不能操作自己！':'Cannot target self!',
'{0}成为了队长！':'{0} is now leader!',
'您的仇人{0}上线了！':'Enemy {0} is online!','您的仇人{0}下线了！':'Enemy {0} went offline.',
'好友推荐':'Suggested Friends','换一批':'Refresh','一键添加':'Add All',
'请输入玩家Name':'Search player name',
'好友已达上限':'Friends list full','对方不在线':'Offline',
// --- Offline Earnings popup (longer forms BEFORE shorter '离线'/'收益') ---
'离线收益':'Offline Earnings','离线时间：':'Offline Time: ','离线时间:':'Offline Time: ',
'收益减弱：':'Reduced Earnings: ','收益减弱:':'Reduced Earnings: ',
'最多累计':'max accumulated ','超过8h':'over 8h','超过':'over ',
'收益':'Earnings',
'Gold卡':'Gold Card','Diamond卡':'Diamond Card',
// ---
'好友':'Friends','总Power:':'Power:','离线':'Offline ','在线':'Online ',
'副本进入次数已满！':'Dungeon limit reached!','上个副本评分太低！':'Last dungeon score too low!',
'副本已达到最高层':'Max dungeon floor','已经在副本里面！':'Already in dungeon!',
'在其它活动里面！':'In another activity!','正在PK！':'In PvP!',
'副本中不能传送':'No teleport in dungeon','活动中不能传送':'No teleport in event',
'道具不足，无法进入副本':'Need items to enter','转生奖励':'Rebirth Reward',
'背包满了，请注意查收！':'Bag full — check mail!','副本奖励':'Dungeon Reward',
'离线奖励':'Offline Reward','奖励领取成功！':'Reward claimed!','使用成功！':'Used!',
'历史排名奖励：':'Historical Rank Rewards:','历史排名奖励':'Historical Rank Rewards',
'奖励预览':'Reward Preview','奖励':'Reward',
'已领取':'Claimed','声望不足':'Low reputation','威望不足':'Low prestige',
'坐骑升阶功能未开放':'Mount upgrade locked','转生后可继续使用！':'Use again after rebirth!',
'今日寻宝次数已满':'Daily treasure limit','藏宝地空空如也！':'Treasure spot empty!',
'空间破碎，进入了未知异域！':'Space shattered!','抽奖次数不足':'Low lottery attempts',
'寻宝获得了{0}':'Found: {0}','已签到':'Checked in',
'今天已参与火眼金睛活动':'Sharp Eye done today','火眼金睛活动未开始':'Sharp Eye not started',
'没有权限':'No permission','成就奖励已领取':'Achievement claimed',
'装备升星成功':'Star-up success!','装备升星失败':'Star-up failed',
'该装备不能升星':'Cannot star up','没有升星材料':'No star-up mats',
'购买失败':'Buy failed','可购买次数不足':'Buy limit reached',
'启用称号失败':'Title activate failed','你已经有该称号':'Already have title',
'你没有该称号':'No such title','你正在使用该称号':'Title already active',
'传功活动未开始':'Training not started','宗主修改了公告：{0}':'Guild notice: {0}',
// --- Chat system ---
'该玩家不在线或不存在！':'Player offline/not found!','您已被禁止发言！':'You are muted!',
'世界聊天功能{0}级开放！':'World chat: Lv.{0}+','您说话太快了，请休息一下！':'Slow down!',
'私聊功能{0}级开放！':'PM: Lv.{0}+','不能和自己聊天！':'Cannot chat with self!',
'宗门聊天功能{0}级开放！':'Guild chat: Lv.{0}+',
// --- Attribute stats ---
'极品属性':'Bonus Stats','铸魂属性':'Soul Stats','套装效果':'Set Effect',
'强化等级':'Enh Level','强化石':'Enh Stone',
'攻击增加':'ATK+','防御增加':'DEF+','破甲增加':'Pen+','命中增加':'Hit+',
'闪避增加':'Eva+','暴击增加':'Crit+','坚韧增加':'TEN+','气血增加':'HP+',
'每5级攻击':'ATK/5Lv','每5级气血':'HP/5Lv','每5级防御':'DEF/5Lv',
'每5级破甲':'Pen/5Lv','每5级命中':'Hit/5Lv','每5级闪避':'Eva/5Lv',
'每5级暴击':'Crt/5Lv','每5级坚韧':'TEN/5Lv',
'蓝冥石(1级)':'Sapphire Lv.1','蓝冥石(2级)':'Sapphire Lv.2',
'蓝冥石(3级)':'Sapphire Lv.3','蓝冥石(4级)':'Sapphire Lv.4',
'蓝冥石(5级)':'Sapphire Lv.5','蓝冥石(6级)':'Sapphire Lv.6',
'蓝冥石(7级)':'Sapphire Lv.7','蓝冥石(8级)':'Sapphire Lv.8',
'蓝冥石(9级)':'Sapphire Lv.9','蓝冥石(10级)':'Sapphire Lv.10',
'血精石(1级)':'Blood Crystal Lv.1','血精石(2级)':'Blood Crystal Lv.2',
'血精石(3级)':'Blood Crystal Lv.3','血精石(4级)':'Blood Crystal Lv.4',
'血精石(5级)':'Blood Crystal Lv.5','血精石(6级)':'Blood Crystal Lv.6',
'血精石(7级)':'Blood Crystal Lv.7','血精石(8级)':'Blood Crystal Lv.8',
'血精石(9级)':'Blood Crystal Lv.9','血精石(10级)':'Blood Crystal Lv.10',
// Gem full HTML entries MUST precede the simple prefix entry below:
'可在"锻造-宝石"中镶嵌\n攻击<font color=\'#37B700\'>+75</font>\n战力<font color=\'#37B700\'>+300</font>':'Socket in "Forge - Gems " for Attack <font color=\'#37B700\'>+75</font> and Power <font color=\'#37B700\'>+300</font>',
'可在"锻造-宝石"中镶嵌\n攻击<font color=\'#37B700\'>+150</font>\n战力<font color=\'#37B700\'>+600</font>':'Socket in "Forge - Gems " for Attack <font color=\'#37B700\'>+150</font> and Power <font color=\'#37B700\'>+600</font>',
'可在"锻造-宝石"中镶嵌':'Inlay in Forge-Gems',
'激活称号':'Activate Title',
'生命恢复':'HP Regen','伤害加深':'DMG Amp','伤害减免':'DMG Reduce',
'暴击几率':'Crit Rate','命中几率':'Hit Rate','闪避几率':'Evasion Rate',
'暴击加成':'Crit Bonus','经验加成':'EXP Bonus',
'气血上限':'Max HP','气血':'HP',
'攻击':'ATK','防御':'DEF','破甲':'Pen',
'命中':'Hit','闪避':'Eva','暴击':'Crit','坚韧':'TEN',
'战力':'Power','等级':'Level','移动':'Speed',
'生命上限':'Max HP','生命':'HP',
'伤害加成':'DMG Bonus',
'未激活':'Inactive','已激活':'Active',
'普通':'Normal','精英':'Elite','史诗':'Epic','传说':'Legendary',
'次数不足':'Insuf. attempts','银币不足':'Insuf. silver','元宝不足':'Insuf. gems',
'武器':'Weapon','项链':'Necklace','戒指':'Ring',
'腰带':'Belt','头盔':'Helmet','铠甲':'Armor','手套':'Gloves','鞋子':'Boots',
'查看属性':'View Attrs','一键装备':'One-key Equip',
'角色':'Character','背包':'Backpack','仓库':'Storage',
'出售':'Sell','丢弃':'Discard','使用':'Use',
'品质':'Quality','绑定':'Bound','未绑定':'Unbound',
// --- Scene names with component-word conflicts (must precede 经验/银币/副本/盟会) ---
'银币副本':'Silver Dungeon','经验副本':'EXP Dungeon',
'击杀':'Kill','经验':'EXP','银币':'Silver','元宝':'Gems',
'掉落':'Drop','采集':'Gather','怪物':'Monster','场景':'Scene',
'气血：':'HP:','攻击：':'ATK:','防御：':'DEF:',
// --- Common UI ---
'开始游戏':'Start Game','进入游戏':'Enter Game','创建角色':'Create Char',
'确定':'OK','取消':'Cancel','关闭':'Close','返回':'Back','分钟':'min','回城':'Return',
'改名卡':'Rename Card','已幻化':'Transformed','一键进阶':'One-click Advance','悟性丹':'Aptitude Pill','预览':'Preview','请输入新名字：':'Enter new name:','请输入新名字:':'Enter new name:',
'名字最长5个字':'Max 5 characters','现任掌门：':'Master: ','虚位以待':'Vacant',
'钢铁之心':'Steel Heart','钻石特权加成':'Diamond Privilege Bonus ',
// --- Spirit Pet names ---
'墨宠小Q':'Ink Pet Q','铠甲龙龟':'Dragon Turtle','猎空':'Sky Hunter',
'蚩尤战车':'Chiyou Chariot','无心刺客':'Heartless Assassin',
'熔岩巨兽':'Lava Beast','异火魔灵':'Hellfire Wraith','上古巨猿':'Ancient Ape',
'墨宠':'Ink Pet',
'升级':'Level Up','装备':'Equip','镶嵌':'Inlay','宝石':'Gem','铸魂':'Soul Cast','任务':'Quest',
'九霄塔':'Sky Tower','演武场':'Arena','金玉堂':'Treasure Hall',
'盟会守军':'Guild Guard','盟会守卫':'Guild Defender',
'挑战':'Challenge','关卡排名':'Stage Rank','盟会':'Guild',
'第':'Ch.','级':'Lv.','关卡':'Level','关':' Stage','层':'Floor',
'爬塔副本':'Tower Dungeon','聚元副本':'Origin Dungeon',
'全民副本':'All-Server Dungeon','剧情副本':'Story','副本':'Dungeon','全民':'All-Server',
'剧情':'Story',
'珍稀掉落':'Rare Drops',
'铸魂配置出错，请联系GM更新配置！':'Soul Cast cfg error - contact GM!',
'伤害':'DMG','血量':'HP','技能':'Skill','冷却':'CD','强化':'Enh',
// --- Task names (pure Chinese — no pre-translated component words) ---
'初试身手':'First Steps','小试牛刀':'Warm Up','扑朔迷离':'Mysterious',
'凌烟问道':'Hall Quest','凌烟阁寻宝':'Hall Treasure Hunt','英雄试炼':'Hero Trial',
'凌烟阁':'Lingyan Hall','寻宝':'Treasure Hunt',
'冲脉':'Meridian Rush','专属VIP商城':'VIP Exclusive Store','专属礼包':'Exclusive Pack','金蟾聚宝':'Golden Toad Treasure','免费补签':'Free Sign-in',
'专属':'Exclusive ','立即':'Now ',
'购买':'Purchase','消费':'Spend',
'累计签到':'Total Check-ins:','可补签到':'Make-up Sign-ins:','签到':'Sign In',
'限购：':'Limit: ','购买总价：':'Total Price: ',
'庶式令牌':'Common Token','金玉令牌':'Premium Token','令牌':'Token',
'宠物进阶丹':'Pet Advance Pill','进阶丹':'Advance Pill','突破丹':'Breakthrough Pill','积元丹':'Origin Pill',
'面对强敌':'Face a Foe','突飞猛进':'Rapid Growth','从容应对':'Steady',
'黑夜降临':'Night Falls','声名鹊起':'Rising Fame','深陷重围':'Surrounded',
'阁主试炼':'Hall Master Trial','加入一个盟会':'Join a Guild','浴血抗敌':'Bloody Battle',
'学成下山':'Training Complete','初探缥缈录':'First Dungeon','切磋武艺':'Sparring',
'琅琊练体':'Langya Training','试炼开始':'Trial Begins','独孤试炼':'Lone Trial',
'师兄弟切磋':'Brother Sparring','老阁主的惩罚':'Master\'s Punishment',
'刺探敌情':'Spy on Enemy','江湖秘闻':'Jianghu Secrets','独闯决神殿':'Solo Temple',
'路遇阻挠':'Road Blocked','神殿奇闻':'Temple Tales','龙门渡之行':'Dragon Gate Journey',
'决神试炼':'Divine Trial','凌云问道':'Lingyun Quest','凌云奇遇':'Lingyun Adventure',
'登顶凌云山':'Summit Lingyun','夜探孤影楼':'Shadow Tower Night','孤声飘影':'Shadow Echo',
'再探山海阁':'Sea Hall Revisit','捕风捉影':'Chasing Shadows','孤影秘闻':'Shadow Secrets',
'玉门关军报':'Jade Gate Report','再会玉门关':'Jade Gate Return','长河落日':'River Sunset',
'整装待发':'Ready to Go','风起长林':'Wind in Changlin','前线补给':'Frontline Supply',
'沉船迷案':'Shipwreck Mystery','鬼火幽冥':'Ghost Fire','势如水火':'Fire and Water',
'宋浮反水':'Betrayal','问道琅琊':'Langya Quest','扶风医堂':'Fufeng Clinic',
'及时赶到':'Arriving in Time','转生之路':'Rebirth Path','水落石出':'Truth Revealed',
'长林军魂':'Changlin Warriors','河堤查案':'Riverside Investigation',
'山海问道':'Sea Hall Quest','兄弟相见':'Brothers Meet','危机重重':'Crisis',
'江湖势力':'Jianghu Forces','江湖传闻':'Jianghu Rumors','盟会考验':'Guild Test',
// --- Post-translation: rank suffix (第→Ch. already fired, 名=place) ---
'Ch.1名':'Rank #1','Ch.2-3名':'Rank #2-3','Ch.4-10名':'Rank #4-10',
'Ch.11-50名':'Rank #11-50','Ch.51-100名':'Rank #51-100','Ch.101-200名':'Rank #101-200',
'Ch.101-500名':'Rank #101-500','Ch.501-1000名':'Rank #501-1000','Ch.201-500名':'Rank #201-500',
// --- Mixed keys: post-translation combos (components ran before these) ---
'可Smelt ':'can Smelt ','件Equip':'x Equip','的DMG':' DMG','HP回复':'HP Regen',
'Pet现世':'Pet Summon',
'x目标造成':'x targets ','ATK目标':'ATK targets ','CD时间':'CD ','Crit率':'Crit Rate ',
'UseSkill一定概率':'Using Skill: chance to ','NormalATK':'normal attack',
'Guild Rank达到2阶':'Guild Rank 2','Guild Rank达到3阶':'Guild Rank 3',
'Ch.一Guild':'Top Guild','加入一个Guild':'Join a Guild',
'Skill满级时':'(max level)','Skill总Level':'Skill Level Total ','一本Skills':'Skill Books',
'Enh一次':'Enhance x1 ','Stage开启':'Stage Unlock',
'Power达到':'Reach Power ','Challenge个人':'Challenge Solo ',
// --- Component words (order: longer patterns first) ---
'夺取':'Obtain ','夺回':'Reclaim ','碎片':' Shard','熔炼':'Smelt ','进阶':'Upgrade ','升到':'Reach ',
'10阶':'Rank 10 ','9阶':'Rank 9 ','8阶':'Rank 8 ','7阶':'Rank 7 ','6阶':'Rank 6 ',
'5阶':'Rank 5 ','4阶':'Rank 4 ','3阶':'Rank 3 ','2阶':'Rank 2 ','1阶':'Rank 1 ','阶':'Rank',
'激活':'Activate ','穿戴':'Wear ','个人':'Solo ','全身':'Full ',
'普通捐献':'Normal Donation','高级捐献':'Premium Donation','捐献':'Donate','贡献':' pts',
'剩余次数':'Remaining: ','次数':' count','次':'x','寻找':'Find ','无双':'Peerless ',
'不可':'cannot ','可以':'can ','可':'can ',
'传闻':' Rumor','秘闻':' Secrets','风声':' Rumors','一次':'x1 ','一颗':' ',
// --- Landlord (斗地主) feature ---
'苦工干活时间满释放会自动提取EXP':'Laborer auto-extracts EXP when work time is full',
'保护时间内不可反抗或解救':'Protection time — cannot resist or be rescued',
'苦工名称：':'Laborer Name: ',
'苦工干活':'Laborer Working',
'苦工':'Laborer ',
'提取经验':'Extract EXP',
'最新动态':'Recent Activity',
'今日抓捕':'Today\'s Captures',
'今日':'Today ',
'干活':'Working',
'压榨':'Squeeze',
'抓捕':'Capture',
'释放':'Release',
'提取':'Extract ',
'身份':'Identity',
'信息':'Info',
// --- Task buttons & chat ---
'膜拜':'Worship','互动':'Interact','斗地主':'Landlord',
'领取':'Claim','前往':'Go','发送':'Send',
'系统':'System','世界':'World',
'飙升':'Boost ','榜':' Rank',
// --- Task status & common UI labels ---
'(完成)':'(Done)','进行中':'In Progress','查看排名':'View Ranking',
'历史排名':'Historical Ranking',
'我的排名：':'My Rank: ','我的排行：':'My Rank: ','盟内排名：':'Guild Rank: ',
'排名':'Ranking','名字：':'Name: ','名字':'Name',
'请输入新Name: ':'Enter new name:','请输入新Name:':'Enter new name:',
'1RankDisciple':'Rank 1 Disciple','2RankDisciple':'Rank 2 Disciple',
'3RankDisciple':'Rank 3 Disciple','4RankDisciple':'Rank 4 Disciple','5RankDisciple':'Rank 5 Disciple',
'Rank 1Disciple':'Rank 1 Disciple','Rank 2Disciple':'Rank 2 Disciple',
'Rank 3Disciple':'Rank 3 Disciple','Rank 4Disciple':'Rank 4 Disciple','Rank 5Disciple':'Rank 5 Disciple',
'Guild Contribution:':'Contrib:','Guild Contribution':'Contrib',
'Guild Power:':'Pwr:','Guild Power ':'Pwr: ','Guild Power':'Pwr:',
'通关：':'Clear: ','剩余时间：':'Remaining: ','剩余时间':'Remaining','时间：':'Time: ','盟贡：':'Contrib: ','盟贡':' Guild Contrib',
'永久':'Permanent','小时':'h ',
'Requires level ':'Req. Lv.','Available at level ':'Req. Lv.','Available at Lv.':'Req. Lv.',
' to challenge':'',
'挑战次数不足':'Attempts insufficient','先完成任务':'Finish tasks first',
'活动未开启':'Event not started','背包已满，是否一键熔炼':'Bag full — smelt all?',
'恭喜你挑战胜利！':'Challenge victory!','连胜':'Win Streak',
// --- NPC names (npc_data) ---
'邱莫言':'Qiu Moyan','花满堂':'Hua Mantang','沈万山':'Shen Wanshan',
'大风':'Da Feng','战北野':'Zhan Beiye','神秘':'Mysterious ','长孙无极':'Changsun Wuji',
'宗越':'Zong Yue','云痕':'Yun Hen',
// --- Feature names (additions) ---
'经脉':'Meridian',
// --- Loot / reward notifications ---
'获得：':'Obtained: ','获得了':'obtained ','获得':'Obtained ',
// --- Rebirth / passive unlock ---
'转生：':'Rebirth: ','5转':'5th','4转':'4th','3转':'3rd','2转':'2nd','1转':'1st','0转':'0',
'雪疥虫':'Frost Bug',
// --- Skill description components ---
'自身':'Self ','时触发':' triggers,','持续':'Lasts ','冷却时间':'CD ','增加目标':'Add Target',
'免伤加成':'DMG Reduce+','对前方':'vs front ','对附近':'AOE ','个目标造成':'x targets ',
'范围：':'Range: ','目标：':'Target: ','目标':'target ','使主target ':'on target: ',
'本轮触发效果：':'Effect: ','触发效果：':'Effect: ',
'造成':'deals ','一定概率':'with a chance to ','降低':'-','升高':'+','提升':' +',
'沉默':'Silenced','眩晕':'Stunned','中毒':'Poisoned','冰冻':'Frozen','只能':'can only ',
'普通攻击':'normal attack','普攻':'basic attack','扇形':'Fan','圆形':'Circle',
'壹':'1','贰':'2','叁':'3','肆':'4','伍':'5','陆':'6','柒':'7','捌':'8','玖':'9','拾':'10',
'，':', ','秒':'s','个':'x','再战':'Fight Again\n',
// NOTE: 对BOSSDMG must precede 对BOSS (伤害→DMG fires first turning 对BOSS伤害→对BOSSDMG)
'对BOSSDMG':'vs BOSS DMG','对BOSS':'vs BOSS ',
// --- Monster names (mon_data) ---
// Compound names first (before shorter component-word entries below)
'魔化修罗':'Demon Shura','璇玑密探':'Jade Spy','白衣剑客':'White Swordsman',
'荒原狼':'Wasteland Wolf','蒙面刺客':'Masked Assassin','大肚守军':'Gate Guard',
'琅琊阁弟子':'Langya Disciple','启竹溪守军':'Qizhu Guard','屠刀刺客':'Blade Assassin',
'黑衣刺客':'Shadow Assassin','大同叛军':'Datong Rebel','暗夜刺客':'Night Assassin',
'禁军':'Imperial Guard','曹少钦':'Cao Shaoqin',
'文神雕像':'Scholar Statue','武神雕像':'Warrior Statue','文武化身':'Sage Avatar',
'玄武':'Xuanwu','蒙烈':'Meng Lie','邪妖天师':'Evil Warlock',
'炼狱将魂':'Infernal Soul','岩灵傀儡':'Stone Golem',
'炎火妖姬':'Flame Demoness','潮汐将魂':'Tide Soul',
'萧平章':'Xiao Pingzhang','云魂':'Cloud Soul','雾隐':'Mist Phantom',
'星辉':'Starlight','修罗':'Shura','千绵':'Qian Mian','蓝月':'Blue Moon',
'狂狮':'Fierce Lion','铁成':'Tie Cheng','释羽':'Shi Yu','司徒':'Situ','少钦':'Shao Qin',
'月魄':'Moon Soul','玉衡':'Yu Heng','寻亦':'Xun Yi','烟杀':'Smoke Kill',
'玄策':'Xuan Ce','墨羽':'Ink Wing','圣灵':'Holy Spirit','血影':'Blood Shadow',
'昊阳':'Hao Yang','擎天':'Sky Pillar','御皇神':'Imperial God',
'攻城援军':'Siege Support','攻城勇士':'Siege Warrior',
'岩魂':'Rock Soul','炎魂':'Flame Soul','海岩傀儡':'Sea Golem',
'缥缈录小怪':'Dungeon Minion',
// --- Title names (title_data) ---
'初露峥嵘':'Rising Star','第一盟会':'Top Guild','入室弟子':'Inner Disciple',
'谁与争锋':'Unrivaled','笑傲江湖':'Jianghu Legend','木秀于林':'Outstanding',
'一枝独秀':'Stand Alone','刀光剑影':'Blade Master','孤影傲世':'Lone Shadow',
'英勇神武':'Valiant','神机百变':'Mastermind','丹凤朝阳':'Rising Phoenix',
'一骑绝尘':'Supreme Rider','出神入化':'Transcendent','命格无双':'Destiny Master',
'电光火石':'Lightning Fast','流光溢彩':'Radiant','横扫千军':'Army Sweeper',
'独孤求败':'Lone Champion','登峰造极':'Pinnacle','惊鸿绝影':'Fleeting Shadow',
'超凡出神':'Divine Spirit','御龙在天':'Dragon Rider',
// --- Scene / dungeon names (scene_data) ---
'龙门渡':'Dragon Ferry','凌云山':'Lingyun Mt.','玉门关':'Jade Gate Pass',
'金陵':'Jinling','七宿山':'Seven Stars Mt.','乾陵魔窟':'Demon Cave',
'江湖风云':'Jianghu Storm','守城神将':'City Guardian',
'皇城对战':'Imperial Battle','皇城战':'Imperial War','缥缈录':'Misty Records',
// --- Guild role labels ---
'弟子':'Disciple','宗主':'Guild Master','护法':'Guild Elder','长老':'Elder','决神殿':'Divine Temple',
// --- Mixed key: post-translation combo (魔神→Devil Raid fires first) ---
'Devil Raid抢夺':'Devil Raid',
// --- Robot player name components (common words in bot names) ---
'幻影':'Phantom ','无尽':'Endless ','无极':'Boundless ','天劫':'Sky Tribulation ',
'天绝':'Sky End ','天锐':'Sky Edge ','孤傲':'Lone Pride ','月蚀':'Eclipse ',
'逍遥':'Free Spirit ','沧狼':'Blue Wolf ','浣花':'Lotus ','流星':'Meteor ',
'潜龙':'Hidden Dragon ','独醉':'Lone Drunk ','嗜血':'Bloodthirsty ','暗影':'Dark Shadow ',
'增加':'+ ',
// --- Entries from cw.txt (placed after 增加, before 万) ---
'目标地图不支持传送':'Teleport not supported on target map',
'装备等阶大于养成等阶':'Equipment tier exceeds upgrade tier',
'上古巨猿':'Ancient Giant Ape',
'七星龙渊':'Seven-Star Dragon Abyss',
'参与':'Join',
'神秘墨宠':'Mysterious Pet',
// Partial boss names — compound forms (潮汐将魂/邪妖天师/炼狱将魂) handled above
'潮汐将':'Tide General',
'邪妖天':'Demonic Heaven',
'炼狱将':'Infernal General',
'姿势不对，无法传送6%':'Wrong posture, unable to teleport 6%',
'关开启':' Stage Unlock','开启':' Unlock',
'一万':'10K','两万':'20K','三万':'30K','五万':'50K','十万':'100K',
'万':'0K',
// --- Final-pass combos (must be last: depend on 次→x and 装备→Equip having already fired) ---
'一xEquip':'1x Equip','一x Equip':'1x Equip'
};
// Load admin-managed extra translations at startup (non-blocking).
// Entries are merged into _m so _rep() picks them up automatically.
// File is managed via admin.php Translation tab → Extra JS Translations.
(function(){
    var xr=new XMLHttpRequest();
    xr.open('GET','extra_translations.json?_='+Date.now(),true);
    xr.onload=function(){
        try{
            var ex=JSON.parse(xr.responseText||xr.response);
            if(ex&&typeof ex==='object'){
                var ks=Object.keys(ex);
                if(ks.length>0){
                    // Rebuild _m: extra entries first, sorted by length desc so longer
                    // more-specific keys are matched before shorter generic ones.
                    // Extra entries override translate.js entries when keys overlap.
                    ks.sort(function(a,b){return b.length-a.length;});
                    var nm={};
                    ks.forEach(function(k){nm[k]=ex[k];});
                    Object.keys(_m).forEach(function(k){if(!nm.hasOwnProperty(k))nm[k]=_m[k];});
                    _m=nm;
                }
            }
        }catch(_){}
    };
    xr.send(null);
})();
// v93: Block premature WebSocket connections that fire on page load before auth.
// Polls until Manager.socket is available, then wraps init() so it's a no-op
// until _cwSocketReady() is called by the login patch on auth success.
// After first auth, restores the real init so reconnects work without re-auth.
(function(){
    function _tryGuard(){
        if(typeof Manager==='undefined'||!Manager.socket||!Manager.socket.init||Manager.socket.__cwG)return;
        Manager.socket.__cwG=true;
        var _ri=Manager.socket.init.bind(Manager.socket);
        Manager.socket.init=function(){/* blocked until auth */};
        window._cwSocketReady=function(){
            Manager.socket.init=_ri;
            try{_ri();}catch(e){}
        };
    }
    [0,100,500,1000,2000,4000].forEach(function(d){setTimeout(_tryGuard,d);});
})();
var _npcN = {
  '一刀': 'OneSaber',
  '一刀99': 'OneSaber99',
  '一哥': 'OneBrother',
  '七夜飞燕': 'NightSevenFlyingSwallow',
  '三生别离': 'SamsaraPartingApart',
  '三生红舞': 'SamsaraRedDance',
  '上官美景': 'ShangguanBeautyScenery',
  '不归': 'NeverReturn',
  '不死子画': 'NeverDeathSonPainted',
  '不死许诺': 'NeverDeathPromisePromise',
  '东方杜若': 'OrientDuLike',
  '东极无霞': 'FarEastVoidGlow',
  '东楼': 'EastTower',
  '东郭小倩': 'DongguoLittleWinsome',
  '东里若颜': 'EastLiLikeFace',
  '东野月心': 'WildsMoonHeart',
  '丝弦': 'Strings',
  '临风玉衣': 'OverWindJadeRobe',
  '临风阡陌': 'OverWindPathPath',
  '为所欲为': 'Unstoppable',
  '丽娅': 'Lia',
  '丽雅': 'Leya',
  '乐正子晨': 'YuezhengSonDawn',
  '乘龙如玉': 'RidingLikeJade',
  '乘龙孤独': 'RidingSolitary',
  '九天应怜': 'SkyAnswerPity',
  '九歌': 'Ode',
  '书墨云歌': 'InkmasterCloudSong',
  '乱世忘忧': 'ChaosForgottenSorrow',
  '乾天尘烟': 'HeavenDustMist',
  '乾天神侠': 'HeavenDivineHero',
  '云海香寒': 'CloudSeaFragrantCold',
  '云游凉川': 'WandererCoolStream',
  '云游阡陌': 'WandererPathPath',
  '云烟': 'Misty',
  '仗剑吟风': 'SwordBearerChantWind',
  '仗剑小北': 'SwordBearerLittleNorth',
  '仙风入梦': 'CelestialWindEnterDream',
  '令狐无期': 'LinghuVoidHope',
  '仲孙夕水': 'ZhongsunEveWater',
  '仲孙子鱼': 'ZhongsunSonFish',
  '仲长大帅': 'ZhongchangGrandMarshal',
  '仲长飞雨': 'ZhongchangFlyingRain',
  '伏龙若离': 'CrouchingLikeApart',
  '伏龙长天': 'CrouchingEternalSky',
  '伐天妙依': 'ConquerSkyWondrousYi',
  '伐天阿飞': 'ConquerSkyAFlying',
  '佳佳': 'Jia',
  '佳凝': 'JadeFlow',
  '佳慧': 'JadeGrace',
  '佳期': 'JadeDate',
  '佳音': 'JadeMelody',
  '使者': 'Envoy',
  '依云': 'YiCloud',
  '依依': 'Yiyi',
  '依晓': 'YiDawn',
  '依晨': 'YiMorning',
  '侠客': 'Knight',
  '俊逸伯牙': 'GallantLordFang',
  '俊逸玉环': 'GallantJadeRing',
  '修罗': 'Asura',
  '倚楼': 'Tower',
  '倩兮': 'QianXi',
  '倩文': 'QianWen',
  '倾城': 'Alluring',
  '倾尽如烟': 'GracefulAllLikeMist',
  '倾尽孤鹤': 'GracefulAllLoneCrane',
  '倾心': 'Devoted',
  '倾月': 'Lunar',
  '傲慢元芳': 'ProudSlowYuanFragrant',
  '傲慢红笺': 'ProudSlowRedNote',
  '傲霜': 'FrostProud',
  '光光': 'Bright',
  '光明盈袖': 'BrilliantFullSleeve',
  '光明长风': 'BrilliantEternalWind',
  '公冶千桦': 'GongyeThousandBirch',
  '公冶君郎': 'GongyeNobleLad',
  '公孙狼主': 'GongsonWolfChief',
  '公孙玉莹': 'GongsonJadeJade',
  '公户小溪': 'GonghuLittleBrook',
  '公玉小蝶': 'LordJadeLittleButterfly',
  '公羊昭伯': 'GongyangBrightLord',
  '公羊若琳': 'GongyangLikeLin',
  '公良小小': 'LordFineLittleLittle',
  '公西凡心': 'GongxiMortalHeart',
  '兰翘': 'OrchidCurl',
  '冥想如意': 'DarkDreamLikeWill',
  '冥想宗保': 'DarkDreamPatriarchGuard',
  '冰儿': 'FrostChild',
  '冰封兰舟': 'FrozenSealOrchidBoat',
  '冰封长青': 'FrozenSealEternalAzure',
  '冷香': 'ColdFragrant',
  '凌晨一点': '1AM',
  '凌薇': 'SoarFern',
  '凌霄芊儿': 'SoarSkyLushChild',
  '凌音': 'SoarSound',
  '凝夕': 'FrozenEve',
  '凤吟': 'PhoenixChant',
  '凤鸣沧月': 'PhoenixCallAzureMoon',
  '初云': 'FirstCloud',
  '初夏': 'FirstSummer',
  '初晓': 'FirstDawn',
  '初柳': 'FirstWillow',
  '初樱': 'FirstCherry',
  '初音': 'FirstSound',
  '剑侠': 'BladeHero',
  '剑君': 'BladeNoble',
  '剑少': 'BladeYouth',
  '剑屏': 'BladeScreen',
  '剑指君子': 'BladePointNobleSon',
  '剑指玉娆': 'BladePointJadeEnchanting',
  '剑白': 'BladeWhite',
  '剑起听雨': 'BladeRiseListenRain',
  '剑起玉苏': 'BladeRiseJadeSu',
  '勤勤': 'DiligentDiligent',
  '化生苍穹': 'TransformCyanVault',
  '北斗月婵': 'NorthFighterMoonChan',
  '千夜秋萝': 'NightfallAutumnLuo',
  '千年东来': 'ThousandYearEastCome',
  '千年红颜': 'ThousandYearRedFace',
  '千歌': 'ThousandSong',
  '千秋轻愁': 'EternalLightGrief',
  '千羽不群': 'MyriadNeverGroup',
  '千羽丹唇': 'MyriadElixirLips',
  '千里书生': 'FarawayScribeBorn',
  '千里胧月': 'FarawayMistyMoon',
  '南斗吹血': 'SouthFighterBlowBlood',
  '南斗玉翎': 'SouthFighterJadePlume',
  '南歌': 'SouthSong',
  '南秋': 'SouthAutumn',
  '南门小曼': 'NanmenLittleGrace',
  '南雁': 'SouthGoose',
  '卧龙': 'RestingDragon',
  '即墨大帝': 'JimoGrandLord',
  '即墨飞虹': 'JimoFlyingRainbow',
  '卿卿': 'DearDear',
  '叛逆彧卿': 'RebelRebelYuDear',
  '叛逆玉楼': 'RebelRebelJadeTower',
  '古楼': 'AncientTower',
  '古道吟秋': 'AncientWayChantAutumn',
  '古道小刀': 'AncientWayLittleSaber',
  '可心': 'CanHeart',
  '叶落烈风': 'LeafFallenBlazeWind',
  '叶落秋月': 'LeafFallenAutumnMoon',
  '司寇子衿': 'SikouSonCollar',
  '司徒若冰': 'CommandDiscipleLikeFrost',
  '司空小冉': 'MinisterLittleRan',
  '名家': 'NameFamily',
  '君心': 'NobleHeart',
  '含韵': 'HoldRhyme',
  '呼延圣恩': 'HuyanSacredGrace',
  '呼延月影': 'HuyanMoonShadow',
  '咏琪': 'ChantQi',
  '咏诗': 'ChantPoem',
  '唐门如霜': 'TangGateLikeIce',
  '唐门承旭': 'TangGateBearRising',
  '嗜血华音': 'FondBloodSplendidSound',
  '嗜血残阳': 'FondBloodRemnantYang',
  '嘉千': 'FineThousand',
  '嘉嘉': 'FineFine',
  '嘉容': 'FineFace',
  '嘉欣': 'FineGlad',
  '嘉琪': 'FineQi',
  '囡囡': 'GirlGirl',
  '圆圆': 'RoundRound',
  '圣手': 'SacredHand',
  '墨桑': 'InkMulberry',
  '复仇妖灵': 'AgainFoeDemonSpirit',
  '复仇玉嫣': 'AgainFoeJadeYan',
  '夏沫': 'SummerFoam',
  '夏风承志': 'SummerWindBearWill',
  '夏风秋千': 'SummerWindAutumnThousand',
  '夜华': 'NightSplendid',
  '夜弦': 'NightString',
  '夜影司棋': 'NightShadowCommandChess',
  '夜影龙魂': 'NightShadowDragonSoul',
  '夜月': 'NightMoon',
  '夜澜': 'NightWave',
  '夜灵可云': 'NightSpiritCanCloud',
  '夜灵龙神': 'NightSpiritDragonDivine',
  '夜瞳': 'NightPupil',
  '夜神': 'NightDivine',
  '夜雨': 'NightRain',
  '夜风': 'NightWind',
  '大佬换头像': 'GrandOldChangeHeadLike',
  '天乐天野': 'BlissWild',
  '天冰': 'SkyFrost',
  '天子': 'SkySon',
  '天心': 'SkyHeart',
  '天煞破天': 'FiendBreakerSky',
  '天罡似水': 'SkyForceLikeWater',
  '天罡秦川': 'SkyForceQinStream',
  '天龙云铮': 'SkyDragonCloudZheng',
  '天龙伶仃': 'SkyDragonLingMoored',
  '太叔子怡': 'TaishuSonJoyful',
  '太史九真': 'GrandHistoryNineTrue',
  '太史敬才': 'GrandHistoryRevereGenius',
  '太微别离': 'GrandSubtlePartingApart',
  '太微非凡': 'GrandSubtleNotMortal',
  '夫人': 'ManPerson',
  '奔雷传奇': 'ThunderLegendWondrous',
  '奔雷秋水': 'ThunderAutumnWater',
  '奕剑巫罗': 'YiBladeWitchNet',
  '奕剑玉颜': 'YiBladeJadeFace',
  '如萍': 'LikeDuckweed',
  '妙菡': 'WondrousHan',
  '姬云秀': 'PrincessCloudGrace',
  '威震忘川': 'MightThunderForgottenStream',
  '威震玉藻': 'MightThunderJadeAlgae',
  '娆娆': 'EnchantingEnchanting',
  '娇娘': 'TenderLady',
  '娜扎': 'NaBind',
  '娥皇': 'EEmperor',
  '婉伶': 'GentleLing',
  '婉儿': 'GentleChild',
  '婉君': 'GentleNoble',
  '婉婷': 'GentleElegant',
  '婉月': 'GentleMoon',
  '婉清': 'GentleClear',
  '婠婠': 'WanWan',
  '婴宁': 'InfantPeace',
  '婵娟': 'ChanJuan',
  '婷婷': 'ElegantElegant',
  '婷玉': 'ElegantJade',
  '婷萱': 'ElegantLily',
  '子书': 'SonScribe',
  '子夜轻纱': 'MidnightLightGauze',
  '子车若梦': 'ZicheLikeDream',
  '子轩': 'SonPavilion',
  '孤傲冰河': 'SolitaryFrostRiver',
  '孤傲旧年': 'SolitaryOldYear',
  '孤影刑天': 'LoneShadowPunishSky',
  '孤影浅黛': 'LoneShadowShallowKohl',
  '孤笛巧巧': 'LoneFluteCleverClever',
  '孤笛烟客': 'LoneFluteMistTraveler',
  '孤龙沐橙': 'LoneDragonBatheOrange',
  '宇文夕颜': 'YuwenEveFace',
  '安安': 'PeacePeace',
  '安若': 'PeaceLike',
  '完颜若雪': 'WholeFaceLikeSnow',
  '宗政千寻': 'PatriarchThousandSeek',
  '定天卿尘': 'SkyboundDearDust',
  '定天未凉': 'SkyboundNot-yetCool',
  '宛如': 'GracefulLike',
  '宛宛': 'GracefulGraceful',
  '宫商忘情': 'PalaceTradeForgottenSoul',
  '宫商甘露': 'PalaceTradeSweetDew',
  '宫羽': 'PalaceFeather',
  '宰父小云': 'ZaifuLittleCloud',
  '容华': 'FaceSplendid',
  '容瑄': 'FaceXuan',
  '容色': 'FaceColor',
  '容萱': 'FaceLily',
  '寂然有容': 'SilenceSoHaveFace',
  '寂然神话': 'SilenceSoDivineWords',
  '寒冰红鸾': 'ColdFrostRedLuan',
  '寒冰轻侯': 'ColdFrostLightMarquis',
  '寒夜余恨': 'ColdNightRemainingHate',
  '寒夜红莲': 'ColdNightRedLotus',
  '寒月': 'FrostMoon',
  '寒梅': 'ColdPlum',
  '寒江': 'ColdRiver',
  '寒烟': 'ColdMist',
  '寒笑': 'ColdSmiling',
  '寒芒红药': 'ColdRayRedHerb',
  '寒芒随云': 'ColdRayFollowCloud',
  '寒衣红棉': 'ColdRobeRedCotton',
  '寒衣随风': 'ColdRobeFollowWind',
  '寒香': 'ColdFragrant',
  '封寒': 'SealCold',
  '封尘扶风': 'SealDustSupportWind',
  '封尘长姬': 'SealDustEternalPrincess',
  '封狼沐风': 'SealWolfBatheWind',
  '封狼龙葵': 'SealWolfDragonSunflower',
  '封魔亦秋': 'SealDemonAlsoAutumn',
  '封魔沐泽': 'SealDemonBatheMarsh',
  '尉迟千雨': 'YuchiThousandRain',
  '尊者': 'MasterOne',
  '小东': 'LittleEast',
  '小五': 'LittleFive',
  '小哲': 'LittleWise',
  '小天': 'LittleSky',
  '小山': 'LittlePeak',
  '小杰': 'LittleBrilliant',
  '小武': 'LittleWar',
  '小环': 'LittleRing',
  '小羽': 'LittleFeather',
  '小萌': 'LittleSprout',
  '小蛮': 'LittleWild',
  '小飞': 'LittleFlying',
  '小马': 'LittleHorse',
  '屠手': 'SlayerHand',
  '山人': 'PeakPerson',
  '山河云儿': 'PeakRiverCloudChild',
  '山海芊芊': 'PeakOceanLushLush',
  '左丘飞卿': 'ZuoqiuFlyingDear',
  '师师': 'MasterMaster',
  '帝天': 'LordSky',
  '帝妃': 'LordConsort',
  '幻影别绪': 'IllusionShadowPartingThread',
  '幻影天佑': 'IllusionShadowSkyBless',
  '幽冥亦菲': 'DeepDarkAlsoFei',
  '幽冥沐雨': 'DeepDarkBatheRain',
  '幽姿': 'DeepGrace',
  '幽梦': 'DeepDream',
  '幽若': 'DeepLike',
  '幽香': 'DeepFragrant',
  '弥音': 'FillSound',
  '弦音': 'StringSound',
  '归燕': 'ReturnSwallow',
  '彩桦': 'RainbowBirch',
  '彩玉': 'RainbowJade',
  '彩羽': 'RainbowFeather',
  '彼岸印天': 'FarshoreSealSky',
  '彼岸洛川': 'FarshoreLuoStream',
  '御邪朱唇': 'RideSinisterZhuLips',
  '御邪炎帝': 'RideSinisterBlazeLord',
  '微光': 'SubtleLight',
  '微尘': 'SubtleDust',
  '微微': 'SubtleSubtle',
  '微澜': 'SubtleWave',
  '微然': 'SubtleSo',
  '微笑': 'SubtleSmiling',
  '德玛西亚': 'Demacia',
  '心悠': 'HeartSerene',
  '心莹': 'HeartJade',
  '心雨': 'HeartRain',
  '忘书': 'ForgottenScribe',
  '忠义沛慈': 'LoyalJustLushKind',
  '忧伤': 'SorrowWound',
  '念冰': 'ThinkFrost',
  '念慈': 'ThinkKind',
  '怜儿': 'PityChild',
  '怜星': 'PityStar',
  '怜梦': 'PityDream',
  '思卿': 'ThinkDear',
  '思君': 'ThinkNoble',
  '思琪': 'ThinkQi',
  '思甜': 'ThinkSweet',
  '思雨': 'ThinkRain',
  '怡姿': 'JoyfulGrace',
  '怡然': 'JoyfulSo',
  '恨玉': 'HateJade',
  '恬恬': 'QuietQuiet',
  '恭如': 'RespectLike',
  '悠然朱颜': 'SereneSoZhuFace',
  '悠然炎尊': 'SereneSoBlazeMaster',
  '悦心': 'JoyfulHeart',
  '悦溪': 'JoyfulBrook',
  '情丝': 'SoulSilk',
  '情思': 'SoulThink',
  '情愫': 'SoulFond',
  '情痴朵朵': 'SoulDevotedPetalPetal',
  '情痴牧云': 'SoulDevotedHerdCloud',
  '情长': 'SoulEternal',
  '惊涛欢欢': 'StartledSurgeJoyJoy',
  '惊涛牧天': 'StartledSurgeHerdSky',
  '惊鸿': 'StartledSwan',
  '惜云': 'CherishCloud',
  '惜儿': 'CherishChild',
  '惜弱': 'CherishWeak',
  '惜晚': 'CherishLate',
  '惜玉': 'CherishJade',
  '惜羽': 'CherishFeather',
  '愁客': 'GriefTraveler',
  '慕云不悔': 'AdmireCloudNeverRegret',
  '我先跑你们抗': 'IFirstRunYouThemResist',
  '战风': 'BattleWind',
  '拂樱': 'BrushCherry',
  '拓跋公山': 'TuobaLordPeak',
  '拓跋千骨': 'TuobaThousandBone',
  '择天名士': 'DestinyNameKnight',
  '择天洛璃': 'DestinyLuoPrism',
  '挥洒沐秋': 'WaveSprinkleBatheAutumn',
  '挥洒秋瞳': 'WaveSprinkleAutumnPupil',
  '挽香': 'PullFragrant',
  '摇红': 'SwayRed',
  '摩诃天涯': 'VastHorizon',
  '敏敏': 'SwiftSwift',
  '散仙': 'FreeCelestial',
  '斩影灵儿': 'SlayShadowSpiritChild',
  '斩日寻欢': 'SlaySunSeekJoy',
  '斩日未眠': 'SlaySunNot-yetSleep',
  '断刀': 'CutSaber',
  '断念向北': 'CutThinkTowardNorth',
  '断念汐夜': 'CutThinkTideNight',
  '断罪向南': 'CutSinTowardSouth',
  '断罪汐缘': 'CutSinTideFate',
  '断魂明夏': 'CutSoulBrightSummer',
  '断魂汐颜': 'CutSoulTideFace',
  '新妆': 'NewAdorn',
  '无上江寒': 'VoidUpperRiverCold',
  '无上秋波': 'VoidUpperAutumnWave',
  '无始楚离': 'VoidBeginChuApart',
  '无始流离': 'VoidBeginFlowApart',
  '无涯': 'VoidShore',
  '无病': 'VoidIll',
  '无痕': 'VoidMark',
  '无霜': 'VoidIce',
  '旧人': 'OldPerson',
  '时光': 'TimeLight',
  '昆吾灵光': 'KunISpiritLight',
  '明月未迷': 'BrightMoonNot-yetLost',
  '明月杀炎': 'BrightMoonKillBlaze',
  '明楼江北': 'BrightTowerRiverNorth',
  '明楼玄凤': 'BrightTowerMysticPhoenix',
  '明珠': 'BrightPearl',
  '明相江山': 'BrightEachRiverPeak',
  '明相浅念': 'BrightEachShallowThink',
  '明肌': 'BrightSkin',
  '明镜江湖': 'BrightMirrorRiverLake',
  '明镜玄月': 'BrightMirrorMysticMoon',
  '昔人': 'PastPerson',
  '星分扶摇': 'StarPartSupportSway',
  '星璇': 'StarJade',
  '星竹': 'StarBamboo',
  '映桐': 'ReflectPaulownia',
  '映秀': 'ReflectGrace',
  '春秋灵素': 'SpringAutumnSpiritSimple',
  '春花': 'SpringBlossom',
  '春风': 'SpringWind',
  '昭君': 'BrightNoble',
  '昭天秀卿': 'BrightSkyGraceDear',
  '晓晓': 'DawnDawn',
  '晓溪': 'DawnBrook',
  '晓茹': 'DawnRu',
  '晓蓝': 'DawnBlue',
  '晓蕾': 'DawnBud',
  '晓雪': 'DawnSnow',
  '晓霜': 'DawnIce',
  '晓露': 'DawnDew',
  '晚仪': 'LateGrace',
  '晚晴': 'LateClear',
  '晚歌': 'LateSong',
  '晨熙': 'DawnBright',
  '景玉': 'SceneryJade',
  '晴兮': 'ClearXi',
  '晴岚': 'ClearMist',
  '晴川': 'ClearStream',
  '晴空': 'ClearSky',
  '晴雯': 'ClearWen',
  '暗影如忆': 'DarkShadowLikeMemory',
  '暗影孤星': 'DarkShadowLoneStar',
  '暗星云岚': 'DarkStarCloudMist',
  '暗星苍龙': 'DarkStarAzureDragon',
  '暮婉': 'DuskGentle',
  '曼殊': 'GraceSpecial',
  '曼舒': 'GraceEase',
  '月儿': 'MoonChild',
  '月神': 'MoonDivine',
  '朝露': 'DynastyDew',
  '未央': 'Not-yetCenter',
  '朵儿': 'PetalChild',
  '杏儿': 'ApricotChild',
  '极光': 'UltimateLight',
  '林谦': 'GroveHumble',
  '枯叶伊月': 'BarrenLeafSheMoon',
  '枯叶灵风': 'BarrenLeafSpiritWind',
  '柒夏': 'SevenSummer',
  '柔夷': 'GentleYi',
  '柔柔': 'GentleGentle',
  '柔肠': 'GentleHeart',
  '柔荑': 'GentleYi',
  '柳下伊伊': 'WillowLowerSheShe',
  '柳下灵夜': 'WillowLowerSpiritNight',
  '柳絮': 'WillowFluff',
  '栖雁': 'PerchGoose',
  '桃花': 'PeachBlossom',
  '桔梗': 'OrangeStem',
  '梁丘若霖': 'LiangqiuLikeRain',
  '梅妆': 'PlumAdorn',
  '梅月': 'PlumMoon',
  '梦师': 'DreamMaster',
  '梦晓': 'DreamDawn',
  '梦琪': 'DreamQi',
  '梦瑶': 'DreamGem',
  '梦璃': 'DreamPrism',
  '梦蝶': 'DreamButterfly',
  '梦雪': 'DreamSnow',
  '梧桐': 'WutongPaulownia',
  '梨涡': 'PearWhirl',
  '梨花': 'PearBlossom',
  '楚儿': 'ChuChild',
  '楚楚': 'ChuChu',
  '楠楠': 'NanmuNanmu',
  '樵子': 'WoodsmanSon',
  '欢颜': 'JoyFace',
  '欣兰': 'GladOrchid',
  '欣桐': 'GladPaulownia',
  '欧阳七七': 'OuyangSevenSeven',
  '欧阳义山': 'OuyangJustPeak',
  '歆艺': 'XinArt',
  '武尊': 'WarMaster',
  '死神': 'DeathDivine',
  '毅然云芝': 'ResoluteSoCloudZhi',
  '毒手冰冰': 'PoisonHandFrostFrost',
  '毒手狂人': 'PoisonHandWildPerson',
  '沅芷': 'YuanZhi',
  '泛舟': 'FloatBoat',
  '泪妆': 'TearAdorn',
  '洒然狂龙': 'SprinkleSoWildDragon',
  '洒然秋雅': 'SprinkleSoAutumnRefined',
  '洗剑冰依': 'WashBladeFrostYi',
  '洗剑狂徒': 'WashBladeWildDisciple',
  '流星冰夜': 'FlowStarFrostNight',
  '流星狂歌': 'FlowStarWildSong',
  '流殇': 'FlowFallen',
  '浅夏': 'ShallowSummer',
  '浅雪': 'ShallowSnow',
  '浊酒冰雁': 'MuddyWineFrostGoose',
  '浊酒狂魔': 'MuddyWineWildDemon',
  '浑天冰瑶': 'MurkySkyFrostGem',
  '浑天赤龙': 'MurkySkyCrimsonDragon',
  '浣花': 'WashBlossom',
  '浩然': 'VastSo',
  '浮动': 'FloatMove',
  '浮华': 'FloatSplendid',
  '涧月': 'BrookMoon',
  '涵光': 'DeepLight',
  '深愛': 'DeepLove',
  '混世战魂': 'MixWorldBattleSoul',
  '混世秋叶': 'MixWorldAutumnLeaf',
  '混元少白': 'MixYuanYouthWhite',
  '混元百媚': 'MixYuanHundredCharm',
  '淸愁': 'ClearGrief',
  '淺吟': 'ShallowChant',
  '清寒': 'ClearCold',
  '清尘': 'ClearDust',
  '清愁': 'ClearGrief',
  '清欢': 'ClearJoy',
  '清歌': 'ClearSong',
  '清泪': 'ClearTear',
  '清涟': 'ClearRipple',
  '清璇': 'ClearJade',
  '清秋': 'ClearAutumn',
  '清竹': 'ClearBamboo',
  '清荷': 'ClearLotus',
  '清虚红月': 'ClearEmptyRedMoon',
  '清虚醉客': 'ClearEmptyDrunkTraveler',
  '清雪': 'ClearSnow',
  '清霜': 'ClearIce',
  '清露': 'ClearDew',
  '清韵': 'ClearRhyme',
  '渣渣辉': 'ZhaZhaFai',
  '温瞳': 'WarmPupil',
  '游侠': 'WanderingHero',
  '游剑浅笑': 'RoamingShallowSmiling',
  '游剑长苏': 'RoamingEternalSu',
  '湘云': 'XiangCloud',
  '湘妃': 'XiangConsort',
  '湘盈': 'XiangFull',
  '溪月': 'BrookMoon',
  '溪畔': 'BrookBank',
  '潜龙冉冉': 'LurkingRanRan',
  '潜龙长虹': 'LurkingEternalRainbow',
  '澹台若曦': 'TantaiLikeDaybreak',
  '灭魂含香': 'AnnihilateSoulHoldFragrant',
  '灭魂风哥': 'AnnihilateSoulWindBrother',
  '炎汐': 'BlazeTide',
  '烈阳': 'BlazeYang',
  '烟云': 'MistCloud',
  '烟岚': 'MistMist',
  '烟柳': 'MistWillow',
  '烟波': 'MistWave',
  '烟火': 'MistFlame',
  '烟雨': 'MistRain',
  '焚天': 'BurnSky',
  '焚香': 'BurnFragrant',
  '無淚': 'VoidTear',
  '煙火': 'SmokeFlame',
  '煮酒月奴': 'WineMasterMoonSlave',
  '煮雨': 'BrewRain',
  '燕飞': 'SwallowFlying',
  '狂刀': 'WildSaber',
  '狂风': 'WildWind',
  '独孤吟雪': 'LoneChantSnow',
  '独孤弘烈': 'LoneGrandBlaze',
  '独尊冰澜': 'LoneMasterFrostWave',
  '独尊过客': 'LoneMasterPassTraveler',
  '独手苓儿': 'LoneHandLingChild',
  '独手辰东': 'LoneHandStarEast',
  '独步小白': 'LoneStepLittleWhite',
  '独步秀清': 'LoneStepGraceClear',
  '独醉轻寒': 'LoneDrunkLightCold',
  '独醉邪帝': 'LoneDrunkSinisterLord',
  '玄姬': 'MysticPrincess',
  '玄机': 'MysticChance',
  '玉馨': 'JadeFragrant',
  '玲珑': 'LingRong',
  '珞然': 'LuoSo',
  '珠帘': 'PearlCurtain',
  '珠玉': 'PearlJade',
  '琉夏': 'GlassSummer',
  '琉璃': 'GlassPrism',
  '琥珀': 'AmberAmber',
  '琦琦': 'QiQi',
  '琳儿': 'LinChild',
  '琴台': 'LuteStage',
  '琴琴': 'LuteLute',
  '琵琶': 'PiPa',
  '瑾瑜': 'JinJade',
  '瓶儿': 'BottleChild',
  '甜儿': 'SweetChild',
  '申屠盼盼': 'ShentuHopeHope',
  '画心': 'PaintedHeart',
  '画颜': 'PaintedFace',
  '疏影': 'SparseShadow',
  '白帝': 'WhiteLord',
  '白衣归途': 'WhitecloakReturnPath',
  '白衣水月': 'WhitecloakWaterMoon',
  '百里小汐': 'BailiLittleTide',
  '皇侯': 'EmperorMarquis',
  '皇朝秀琴': 'EmperorDynastyGraceLute',
  '皇甫若星': 'HuangpuLikeStar',
  '皓月月如': 'FullmoonMoonLike',
  '盛世清风': 'GrandWorldClearWind',
  '盛世红丝': 'GrandWorldRedSilk',
  '盛名听风': 'GrandNameListenWind',
  '盛名美眷': 'GrandNameBeautyCare',
  '相士': 'EachKnight',
  '相忆': 'EachMemory',
  '相思': 'EachThink',
  '眉姗': 'BrowShan',
  '知音': 'KnowSound',
  '碎星云袖': 'BrokenStarCloudSleeve',
  '神伤': 'DivineWound',
  '神卫': 'DivineGuard',
  '神殇': 'DivineFallen',
  '祭天禅心': 'RiteSkyZenHeart',
  '祭天红妆': 'RiteSkyRedAdorn',
  '离乱红尘': 'ApartChaoticRedDust',
  '离乱青城': 'ApartChaoticAzureCity',
  '离人': 'ApartPerson',
  '离愁': 'ApartGrief',
  '离落': 'ApartFallen',
  '离魂': 'ApartSoul',
  '秋荻': 'AutumnReed',
  '秋蝉': 'AutumnCicada',
  '秋雨': 'AutumnRain',
  '空冥灵狐': 'SkyDarkSpiritFox',
  '童话': 'ChildWords',
  '端木轻烟': 'UprightWoodLightMist',
  '端木阳神': 'UprightWoodYangDivine',
  '竹影': 'BambooShadow',
  '竹盈': 'BambooFull',
  '笑兮': 'SmilingXi',
  '笑笑': 'SmilingSmiling',
  '笙歌': 'ShengSong',
  '笙箫': 'ShengFlute',
  '第五小璐': 'DiwuLittleLu',
  '筱雅': 'XiaoRefined',
  '筱雨': 'XiaoRain',
  '素因': 'SimpleCause',
  '素影': 'SimpleShadow',
  '素心': 'SimpleHeart',
  '素琴': 'SimpleLute',
  '素真': 'SimpleTrue',
  '素素': 'SimpleSimple',
  '素贞': 'SimpleChaste',
  '紫云': 'PurpleCloud',
  '紫仪': 'PurpleGrace',
  '紫妍': 'PurpleLovely',
  '紫嫣': 'PurpleYan',
  '紫宸': 'PurpleThrone',
  '紫川': 'PurpleStream',
  '紫彤': 'PurpleRed',
  '紫微如初': 'PurpleSubtleLikeFirst',
  '紫微孤島': 'PurpleSubtleLoneIsle',
  '紫怡': 'PurpleJoyful',
  '紫月': 'PurpleMoon',
  '紫涵': 'PurpleDeep',
  '紫烟': 'PurpleMist',
  '紫熏': 'PurpleSmoke',
  '紫琼': 'PurpleJade',
  '紫瞳': 'PurplePupil',
  '紫苏': 'PurpleSu',
  '紫英': 'PurpleValiant',
  '紫萝': 'PurpleLuo',
  '紫萱': 'PurpleLily',
  '紫薇': 'PurpleFern',
  '紫薰': 'PurpleFragrant',
  '紫衣': 'PurpleRobe',
  '紫辰': 'PurpleStar',
  '紫铃': 'PurpleBell',
  '紫陌': 'PurplePath',
  '紫霜': 'PurpleIce',
  '紫霞': 'PurpleGlow',
  '紫韵': 'PurpleRhyme',
  '红尘妙嫦': 'RedDustWondrousChang',
  '绛珠': 'CrimsonPearl',
  '绝恋冰魄': 'SupremeLoveFrostSpirit',
  '绝恋刺客': 'SupremeLovePierceTraveler',
  '绫波': 'SilkWave',
  '绮兰': 'SilkOrchid',
  '绮思': 'SilkThink',
  '绮梦': 'SilkDream',
  '绯衣': 'ScarletRobe',
  '绿樱': 'GreenCherry',
  '绿瑶': 'GreenGem',
  '绿竹': 'GreenBamboo',
  '绿萼': 'GreenSepal',
  '罗刹': 'NetFlash',
  '罗离': 'NetApart',
  '罗纱': 'NetGauze',
  '罗衫': 'NetGarment',
  '罗裳': 'NetSkirt',
  '羽裳': 'FeatherSkirt',
  '翔龙无颜': 'SoaringDragonVoidFace',
  '耶律冰凝': 'YeLawFrostFrozen',
  '耶律夜羽': 'YeLawNightFeather',
  '聆风': 'ListenWind',
  '胭脂': 'RougeBlush',
  '致远': 'ElegantFar',
  '舒夜': 'EaseNight',
  '舒悦': 'EaseJoyful',
  '舒扬': 'EaseSoar',
  '舒月': 'EaseMoon',
  '般若': 'LikeLike',
  '花开': 'BlossomOpen',
  '花影': 'BlossomShadow',
  '花月': 'BlossomMoon',
  '花格': 'BlossomLattice',
  '花灵': 'BlossomSpirit',
  '花眠': 'BlossomSleep',
  '花祭': 'BlossomRite',
  '花色': 'BlossomColor',
  '花花': 'BlossomBlossom',
  '花语': 'BlossomSpeak',
  '花铃': 'BlossomBell',
  '花阁': 'BlossomPavilion',
  '花雨': 'BlossomRain',
  '花露': 'BlossomDew',
  '芳尘': 'FragrantDust',
  '芳菲': 'FragrantFei',
  '芷若': 'ZhiLike',
  '芷香': 'ZhiFragrant',
  '苍月': 'CyanMoon',
  '苏茉': 'SuMo',
  '苏铭': 'SuEngrave',
  '若兰': 'LikeOrchid',
  '若初': 'LikeFirst',
  '若彤': 'LikeRed',
  '若楠': 'LikeNanmu',
  '若水': 'LikeWater',
  '若霜': 'LikeIce',
  '茜茜': 'QianQian',
  '茹芸': 'RuYun',
  '荷衣': 'LotusRobe',
  '荼蘼': 'TuMi',
  '莫忆': 'MoMemory',
  '莫愁': 'MoGrief',
  '莫秋': 'MoAutumn',
  '莲儿': 'LotusChild',
  '莲华': 'LotusSplendid',
  '莲柔': 'LotusGentle',
  '莹莹': 'JadeJade',
  '莺歌': 'OrioleSong',
  '菱纱': 'LingGauze',
  '菲儿': 'FeiChild',
  '菲菲': 'FeiFei',
  '萱儿': 'LilyChild',
  '萱叶': 'LilyLeaf',
  '萱容': 'LilyFace',
  '萱萱': 'LilyLily',
  '落寞飞烟': 'FallenLonelyFlyingMist',
  '落落': 'FallenFallen',
  '葬情浅殇': 'HeartbreakShallowFallen',
  '葬情长空': 'HeartbreakEternalSky',
  '虚空云帆': 'EmptySkyCloudSail',
  '虚空红芍': 'EmptySkyRedPeony',
  '蚀日印月': 'ErodeSunSealMoon',
  '蚀日孤云': 'ErodeSunLoneCloud',
  '蛮腰': 'WildWaist',
  '蝶儿': 'ButterflyChild',
  '血色希影': 'BloodColorHopeShadow',
  '衷情': 'HeartSoul',
  '衷肠': 'HeartHeart',
  '衾寒': 'QuiltCold',
  '袭人': 'InheritPerson',
  '記憶': 'RecordRemember',
  '誓血飞霜': 'OathBloodFlyingIce',
  '誓言飞絮': 'OathWordsFlyingFluff',
  '诗曼': 'PoemGrace',
  '诗芸': 'PoemYun',
  '诗诗': 'PoemPoem',
  '诗音': 'PoemSound',
  '说没有就没有': 'TellGoneHaveThenGoneHave',
  '诺言': 'PromiseWords',
  '豪客': 'BoldTraveler',
  '豪杰': 'BoldBrilliant',
  '贝贝': 'ShellShell',
  '贯丘飞飞': 'NobleFlyingFlying',
  '赤帝': 'CrimsonLord',
  '赫连出云': 'HelianExitCloud',
  '赫连长歌': 'HelianEternalSong',
  '轩辕伯喈': 'XuanyuanLordJie',
  '轩辕音尘': 'XuanyuanSoundDust',
  '轻水': 'LightWater',
  '轻蝶': 'LightButterfly',
  '辉煌飞雪': 'RadiantRadianceFlyingSnow',
  '辟尘如夢': 'OpenDustLikeDream',
  '辟尘定远': 'OpenDustSteadyFar',
  '辰君': 'StarNoble',
  '还真': 'ReturnTrue',
  '连城玄鸟': 'LinkCityMysticBird',
  '连城真君': 'LinkCityTrueNoble',
  '连翘': 'LinkCurl',
  '迷蝶': 'LostButterfly',
  '迷音': 'LostSound',
  '追风妃暄': 'ChaseWindConsortWarm',
  '追风斩浪': 'ChaseWindSlayWave',
  '逆世明心': 'RebelWorldBrightHeart',
  '逆世流年': 'RebelWorldFlowYear',
  '逆天妃萱': 'RebelSkyConsortLily',
  '逆天昊天': 'RebelSkyVastSky',
  '逍遥剑晨': 'CarefreeBladeDawn',
  '逍遥红豆': 'CarefreeRedBean',
  '逐月': 'ChaseMoon',
  '逐梦惊羽': 'ChaseDreamStartledFeather',
  '逐梦红泪': 'ChaseDreamRedTear',
  '逝水': 'GoneWater',
  '道君': 'WayNoble',
  '郎君': 'LadNoble',
  '郡主': 'CountyChief',
  '醉城': 'DrunkCity',
  '醉汉': 'DrunkHan',
  '醉眼云意': 'BlearyCloudWill',
  '醉隐书瑶': 'DrunkHiddenScribeGem',
  '采儿': 'GatherChild',
  '采薇': 'GatherFern',
  '重楼陌忆': 'LayerTowerPathMemory',
  '金刚': 'GoldenSteel',
  '金轮玄冰': 'GoldenWheelMysticFrost',
  '金轮羽生': 'GoldenWheelFeatherBorn',
  '钟情': 'BellSoul',
  '钟离夕语': 'ZhongliEveSpeak',
  '钧天名花': 'JunSkyNameBlossom',
  '钧天孤心': 'JunSkyLoneHeart',
  '钴天乐': 'CobaltBliss',
  '铁血安夏': 'IronBloodPeaceSummer',
  '铁血明羽': 'IronBloodBrightFeather',
  '铁骨寻玉': 'IronBoneSeekJade',
  '铁骨明尊': 'IronBoneBrightMaster',
  '铃兰': 'BellOrchid',
  '银光': 'SilverLight',
  '锁心': 'LockHeart',
  '锦仪': 'BrocadeGrace',
  '锦瑟': 'BrocadeHarp',
  '锦秋': 'BrocadeAutumn',
  '长夏破虏': 'EternalSummerBreakerCaptive',
  '长夏风华': 'EternalSummerWindSplendid',
  '长孙若熙': 'EternalSunLikeBright',
  '长生玄影': 'ImmortalMysticShadow',
  '长生风月': 'ImmortalWindMoon',
  '长袖': 'EternalSleeve',
  '闻人若絮': 'WenrenLikeFluff',
  '阑珊': 'RailingCoral',
  '阿力': 'APower',
  '阿古': 'AAncient',
  '阿离': 'AApart',
  '阿紫': 'APurple',
  '陈晓村': 'ChenDawnVillage',
  '陌路纱罗': 'PathPathGauzeNet',
  '降龙回忆': 'DescendDragonReturnMemory',
  '降龙孤城': 'DescendDragonLoneCity',
  '随缘': 'FollowFate',
  '随风': 'FollowWind',
  '隐世欢歌': 'HiddenWorldJoySong',
  '隐世牧尘': 'HiddenWorldHerdDust',
  '隐梦': 'HiddenDream',
  '雁归': 'GooseReturn',
  '雅兰': 'RefinedOrchid',
  '雅妃': 'RefinedConsort',
  '雅意': 'RefinedWill',
  '雅琴': 'RefinedLute',
  '雅芝': 'RefinedZhi',
  '雨乔': 'RainJoe',
  '雨婷': 'RainElegant',
  '雨嫣': 'RainYan',
  '雨季': 'RainSeason',
  '雨柔': 'RainGentle',
  '雨欣': 'RainGlad',
  '雪儿': 'SnowChild',
  '雪宜': 'SnowProper',
  '雪晴': 'SnowClear',
  '雪月': 'SnowMoon',
  '雪沫': 'SnowFoam',
  '雪琪': 'SnowQi',
  '雪瑶': 'SnowGem',
  '雪舞': 'SnowDance',
  '雪见': 'SnowSee',
  '零落伊人': 'ZeroFallenShePerson',
  '零落沧狼': 'ZeroFallenAzureWolf',
  '霸主': 'OverlordChief',
  '霸王': 'OverlordKing',
  '青丝': 'AzureSilk',
  '青云': 'AzureCloud',
  '青儿': 'AzureChild',
  '青婴': 'AzureInfant',
  '青岚玄音': 'AzureMistMysticSound',
  '青岚血魔': 'AzureMistBloodDemon',
  '青川': 'AzureStream',
  '青帝': 'AzureLord',
  '青桐': 'AzurePaulownia',
  '青梅': 'AzurePlum',
  '青琼': 'AzureJade',
  '青瑶': 'AzureGem',
  '青璇': 'AzureJade',
  '青竹': 'AzureBamboo',
  '青羽灵珊': 'AzureFeatherSpiritCoral',
  '青萝': 'AzureLuo',
  '青衣': 'AzureRobe',
  '青阳玄霜': 'AzureYangMysticIce',
  '青阳行云': 'AzureYangWalkerCloud',
  '青雷玉儿': 'AzureThunderJadeChild',
  '青雷行者': 'AzureThunderWalkerOne',
  '青霜': 'AzureIce',
  '青霞': 'AzureGlow',
  '青青': 'AzureAzure',
  '青鸟': 'AzureBird',
  '青鸾': 'AzureLuan',
  '非烟': 'NotMist',
  '韵诗': 'RhymePoem',
  '风云君瑶': 'WindCloudNobleGem',
  '风云展白': 'WindCloudSpreadWhite',
  '风流主将': 'DashingChiefGeneral',
  '风流无烟': 'DashingVoidMist',
  '风炎东辰': 'StormfireEastStar',
  '风炎语嫣': 'StormfireSpeakYan',
  '飘飘': 'FloatFloat',
  '飞仙': 'FlyingCelestial',
  '飞扬云殊': 'FlyingSoarCloudSpecial',
  '飞月': 'FlyingMoon',
  '飞月慕言': 'FlyingMoonAdmireWords',
  '飞月西楼': 'FlyingMoonWestTower',
  '飞鸟': 'FlyingBird',
  '骊歌': 'Black-horseSong',
  '魔师': 'DemonMaster',
  '鲜于子夫': 'XianyuSonMan',
  '鸣月玉如': 'CallMoonJadeLike',
  '鸣月观海': 'CallMoonWatchOcean',
  '鸣玉': 'CallJade',
  '鸳鸯': 'DuckMandarin',
  '鸿蒙云轩': 'SwanMistCloudPavilion',
  '鸿蒙红雨': 'SwanMistRedRain',
  '黄泉无名': 'YellowSpringVoidName',
  '黄泉红袖': 'YellowSpringRedSleeve',
  '黑帝': 'DarkLord',
  '龙吟吹雨': 'DragonChantBlowRain',
  '龙吟峰哥': 'DragonChantSummitBrother',
  '龙武仙儿': 'DragonFistCelestialChild',
  '龙武苍焰': 'DragonFistCyanInferno',
  '龙牙白龙': 'DragonFangWhiteDragon',
  '龙牙风吟': 'DragonFangWindChant',
  '龙舞均瑶': 'DragonDanceEqualGem',
  '龙舞慕白': 'DragonDanceAdmireWhite',
  '龙行苍雷': 'DragonWalkCyanThunder',
  '龙行风露': 'DragonWalkWindDew',
  '龙隐仙芝': 'HiddenDragonCelestialZhi',
  '龙隐白狼': 'HiddenDragonWhiteWolf',
'七夜酒徒': 'NightSevenWineStudent',
  '上官君嗣': 'ShangguanNobleHeir',
  '不易': 'NeverChange',
  '不服找前': 'NeverBowSeekForward',
  '东': 'East',
  '东方七哥': 'OrientSevenBro',
  '东极北辰': 'FarEastNorthStar',
  '东郭三少': 'DongguoThreeYouth',
  '东里神帝': 'EastLiDivineLord',
  '东野北帝': 'WildsNorthLord',
  '乐正子尚': 'YuezhengNobleSon',
  '乘风': 'RidingWind',
  '九天七郎': 'SkySevenLad',
  '书书': 'ScribeScribe',
  '书墨天王': 'InkmasterSkyKing',
  '乱世五郎': 'ChaosFiveLad',
  '云天': 'CloudSky',
  '云海天兵': 'CloudSeaSkySoldier',
  '云龙': 'CloudDragon',
  '人皇': 'PersonEmperor',
  '今晚做头发': 'NowTonightDoHeadHair',
  '仙风德衡': 'CelestialBreeze',
  '令狐仙王': 'LinghuCelestialKing',
  '仲海': 'ZhongHai',
  '侠隐': 'HeroHidden',
  '公子云髻': 'NobleCloudBun',
  '公子郡王': 'NobleRegionKing',
  '公户真人': 'GonghuTruePerson',
  '公玉上人': 'GongYuElder',
  '公良刀狂': 'GongliangSaberMad',
  '公西公祺': 'GongxiBlessed',
  '六道云鬓': 'SixPathsCloudTemple',
  '六道天狼': 'SixPathsSkyWolf',
  '冷风': 'ColdWind',
  '凌霄乐少': 'SkyhighJoyYouth',
  '凤鸣小龙': 'PhoenixCallLittleDragon',
  '剑仇': 'BladeFoe',
  '剑痴': 'BladeDevoted',
  '化生双心': 'TransformTwinHeart',
  '北斗圣皇': 'DipperSacredEmperor',
  '千夜云飞': 'NightfallCloudFlying',
  '千秋云书': 'EternalCloudScribe',
  '南宫云曦': 'NangongCloudDawn',
  '南宫天罗': 'NangongSkyNet',
  '南门六少': 'NanmenSixYouth',
  '叶苏': 'YeSu',
  '司寇德伟': 'SikouVirtuous',
  '司徒巨源': 'SituGiantSource',
  '司空刀魔': 'MinisterSaberDemon',
  '君陌': 'NoblePath',
  '啸天': 'HowlSky',
  '天乐双清': 'BlissTwinClear',
  '天云': 'SkyCloud',
  '天仇': 'Nemesis',
  '天劫少年': 'DoomYouthYear',
  '天劫盈盈': 'DoomFullFull',
  '天地天逸': 'HeavenCarefreeSky',
  '天地语诗': 'HeavenWordsPoem',
  '天师': 'Grandmaster',
  '天影心蓝': 'PhantomBlueHeart',
  '天影无忌': 'PhantomFearless',
  '天机天眉': 'FateSkyBrow',
  '天机神侯': 'FateDivineMarquis',
  '天极少皇': 'ApexYouthEmperor',
  '天极心月': 'ApexHeartMoon',
  '天海心妍': 'EndlessHeartBeauty',
  '天海无双': 'EndlessPeerless',
  '天渊心语': 'AbyssHeartWords',
  '天渊无心': 'AbyssHeartless',
  '天煞心湖': 'FiendHeartLake',
  '天照': 'Radiance',
  '天祭心凌': 'RiteHeartSoar',
  '天祭无尘': 'RiteVoidDust',
  '天绝心兰': 'DoomedHeartOrchid',
  '天绝心魔': 'DoomedHeartDemon',
  '天钧心如': 'BalancePureHeart',
  '天钧文卓': 'BalanceScholar',
  '天锐心海': 'RazorHeartOcean',
  '天锐神将': 'RazorDivineGeneral',
  '天问天影': 'SeekerPhantom',
  '天问少主': 'SeekerYouthChief',
  '太初忆如': 'OriginMemory',
  '太初无间': 'OriginBoundless',
  '太叔幼安': 'TaishuYoungPeace',
  '太子': 'Crown',
  '太玄无我': 'TaiXuanVoidSelf',
  '太玄眉妆': 'TaiXuanBrowAdorn',
  '如山': 'Steadfast',
  '如林': 'Forest',
  '如火': 'Blazing',
  '如风': 'Swift',
  '妖神': 'WitchGod',
  '姬云澈': 'JiCloudClear',
  '子夜云兮': 'MidnightCloudDrift',
  '子车仲简': 'ZicheSecondPlain',
  '子陵': 'ZiLing',
  '孤龙少侠': 'LoneDragonYouthHero',
  '宁缺': 'PeaceMissing',
  '宇文子干': 'YuwenSonStrength',
  '完颜三哥': 'WanyanThreeBro',
  '宗政汉瑜': 'PatriarchHanYu',
  '宫九': 'PalaceNine',
  '宰父刀客': 'ZaifuSaberTraveler',
  '尉迟元明': 'YuchiYuanMing',
  '尊王': 'LordKing',
  '小宝': 'LittleTreasure',
  '山民': 'PeakPeople',
  '山河云起': 'RiversCloudRise',
  '山海耀扬': 'PeaksRadiantSoar',
  '左丘小生': 'ZuoqiuLittleBorn',
  '布衣': 'PlainRobe',
  '师兄': 'SeniorBro',
  '开局一条狗': 'StartingOneDog',
  '忠义大侠': 'LoyalGrandHero',
  '怀远': 'Fargazer',
  '情魔': 'SoulDemon',
  '慕云真仙': 'MuYunTrueCelestial',
  '慕容凌天': 'MurongSoarSky',
  '慕容无泪': 'MurongTearless',
  '摩诃公主': 'VastPrincess',
  '文少': 'ScholarYouth',
  '斩影龙哥': 'SlayShadeDragonBro',
  '无双纯钧': 'PeerlessPureBalance',
  '无尽文秀': 'EndlessScholar',
  '无尽残月': 'EndlessWaningMoon',
  '无影东风': 'ShadowlessEastWind',
  '无影无垢': 'ShadowlessVoidStain',
  '无情凌云': 'RuthlessSoarCloud',
  '无情无依': 'RuthlessLone',
  '无想无花': 'DreamlessVoidBlossom',
  '无想王侯': 'DreamlessKingMarquis',
  '无极剑圣': 'BoundlessBladeSacred',
  '无极无双': 'BoundlessPeerless',
  '无极无缺': 'BoundlessVoidMissing',
  '无畏无心': 'FearlessHeartless',
  '无畏无道': 'FearlessVoidWay',
  '无相无月': 'FormlessVoidMoon',
  '无相王者': 'FormlessKing',
  '无落': 'Rootless',
  '昂天': 'HighSky',
  '昆吾龙少': 'KunwuDragonYouth',
  '明王': 'LightKing',
  '星分五哥': 'StarbornFiveBro',
  '春秋小虎': 'AgesLittleTiger',
  '昭天虎哥': 'SkyGlowTigerBro',
  '最终不改版': 'FinalVersion',
  '月蚀东君': 'EclipseEastNoble',
  '月蚀无恨': 'EclipseVoidHate',
  '朝哥': 'MorningBro',
  '杀手': 'Assassin',
  '杀神': 'Slayer',
  '杜无疆': 'DuBorderless',
  '杜飛雲': 'DuFeiYun',
  '柳白': 'WillowWhite',
  '梁丘上师': 'LiangqiuMaster',
  '武痴': 'WarDevoted',
  '毅然云踪': 'ResoluteSoCloudTrace',
  '沈石': 'ShenShi',
  '流年': 'Fleeting',
  '浪子': 'WaveSon',
  '浪徒': 'WaveStudent',
  '浪漫': 'WaveWide',
  '浮云': 'DriftCloud',
  '海客': 'Seabound',
  '海少': 'OceanYouth',
  '澹台子琰': 'TantaiSonJade',
  '煮酒四海': 'WineMasterFourOcean',
  '狂客': 'WildTraveler',
  '狂潮': 'WildTide',
  '王族': 'KingClan',
  '甘泽': 'SweetBless',
  '申屠飞流': 'ShentuFlyingFlow',
  '百里大少': 'BailiGrandYouth',
  '皇朝小川': 'DynastyLittleStream',
  '皇甫圣君': 'HuangpuSacredNoble',
  '皓月疾风': 'FullmoonSwiftWind',
  '盗帅': 'ThiefLord',
  '看到也不给你': 'NoShareForYou',
  '碎星元帅': 'ShatterStarMarshal',
  '神族': 'DivineClan',
  '神王': 'DivineKing',
  '神皇': 'DivineEmperor',
  '秋生': 'AutumnBorn',
  '空冥风少': 'VoidAbyssWindYouth',
  '笑天': 'SmilingSky',
  '第五义士': 'DiwuJustKnight',
  '策划最靓': 'TopDesigner',
  '素观': 'PureGaze',
  '紫霄双燕': 'PurpleSkyTwinSwallow',
  '紫霄天翔': 'PurpleSkySkyGlide',
  '红尘怜花': 'EarthlyBlossom',
  '翔龙仙君': 'SoaringDragonCelestialNoble',
  '苍松': 'CyanPine',
  '若海': 'Vastness',
  '若羽': 'Feather',
  '落寞飞雨': 'DesolateFlyingRain',
  '血色三郎': 'CrimsonThreeLad',
  '血衣': 'BloodRobe',
  '誓血飞鸿': 'BloodOathFlyingGreat',
  '誓言子歌': 'OathSonSong',
  '贯丘神君': 'NobleDivineNoble',
  '辉少': 'GlowYouth',
  '辉煌子期': 'RadianceSonEra',
  '逸才': 'Prodigy',
  '邪神': 'DarkGod',
  '醉眼凌风': 'BlearySoarWind',
  '醉隐云峥': 'HiddenCloudTowering',
  '醉饮忆然': 'DrunkenMemorySo',
  '醉饮无炎': 'DrunkenVoidBlaze',
  '释天': 'FreeSky',
  '重楼青锋': 'TowerAzureEdge',
  '钟离遂高': 'ZhongliFollowHigh',
  '镇远': 'GuardFar',
  '长孙字山': 'ZhangSunPeak',
  '间客': 'FreeWanderer',
  '闻人文约': 'WenrenScholarAccord',
  '陌尘': 'WayfairDust',
  '陌离': 'Parting',
  '陌路逸风': 'PathlessWanderer',
  '青羽峰少': 'AzureFeatherPeak',
  '飞扬浪人': 'SoaringWavePerson',
  '魔尊': 'DemonLord',
  '魔族': 'DemonClan',
  '鲜于景兴': 'XianyuSceneRise',
  '鹰王': 'EagleKing',
  '齐昊': 'QiHao',
  '龙王': 'DragonKing',
  '龙飞': 'DragonSoar',
};
function _rep(s){
    if(typeof s!=='string'||!s)return s;
    if(_npcN[s])return _npcN[s];
    s=s.replace(/与(.+?)私聊中/,'PM: $1');
    s=s.replace(/第(\d+)名/g,'Rank #$1');
    for(var k in _m)if(s.indexOf(k)>=0)s=s.split(k).join(_m[k]);
    return s;
}
var _an={10:'Speed',11:'Max HP',12:'HP',13:'ATK',14:'DEF',15:'Pen',
    16:'Hit',17:'Eva',18:'Crit',19:'TEN',20:'HP Regen',21:'EXP+',
    22:'DMG+',23:'DMG-',24:'Crit%',25:'CritRes',26:'CritDMG+',
    27:'CritDMG-',28:'Hit%',29:'Eva%',30:'HP%',31:'ATK%',32:'DEF%',33:'Pen%'};
function _fixAttrCVO(){
    if(typeof AttrCVO!=='undefined'&&AttrCVO._data){
        for(var id in _an){var i=AttrCVO._data[parseInt(id)];if(i){i.name=_an[id];i.shortName=_an[id];}}
    }
}
function _patch(){
    if(typeof AttrDescTypeEx!=='undefined'&&AttrDescTypeEx.getAttrName&&!AttrDescTypeEx.__cwP){
        AttrDescTypeEx.__cwP=true;
        var _g=AttrDescTypeEx.getAttrName;
        AttrDescTypeEx.getAttrName=function(id){return _rep(_g.call(this,id));};
    }
    if(typeof AttrVoInfo!=='undefined'&&AttrVoInfo.prototype&&AttrVoInfo.prototype.desc&&!AttrVoInfo.prototype.__cwD){
        AttrVoInfo.prototype.__cwD=true;
        var _d=AttrVoInfo.prototype.desc;
        AttrVoInfo.prototype.desc=function(t,e){return _rep(_d.call(this,t,e));};
    }
    if(typeof HtmlUtil!=='undefined'){
        if(HtmlUtil.setTextFlow&&!HtmlUtil.__cwS){
            HtmlUtil.__cwS=true;var _s=HtmlUtil.setTextFlow;
            HtmlUtil.setTextFlow=function(tf,s){return _s.call(this,tf,_rep(s));};
        }
        if(HtmlUtil.addColorTag&&!HtmlUtil.__cwC){
            HtmlUtil.__cwC=true;var _c=HtmlUtil.addColorTag;
            HtmlUtil.addColorTag=function(t,c){return _c.call(this,_rep(t),c);};
        }
    }
    if(typeof egret!=='undefined'&&egret.HtmlTextParser&&egret.HtmlTextParser.prototype&&!egret.HtmlTextParser.prototype.__cwHP){
        egret.HtmlTextParser.prototype.__cwHP=true;
        var _php=egret.HtmlTextParser.prototype.parser;
        egret.HtmlTextParser.prototype.parser=function(s){return _php.call(this,_rep(s));};
    }
    if(typeof egret!=='undefined'&&egret.TextField&&egret.TextField.prototype){
        var p=egret.TextField.prototype;
        if(!p.__cwT){
            var _td=Object.getOwnPropertyDescriptor(p,'text');
            if(_td&&_td.set){
                p.__cwT=true;
                Object.defineProperty(p,'text',{get:_td.get,set:function(v){_td.set.call(this,_rep(v));},configurable:true,enumerable:_td.enumerable});
            }
        }
        if(!p.__cwH){
            var _hd=Object.getOwnPropertyDescriptor(p,'htmlText');
            if(_hd&&_hd.set){p.__cwH=true;Object.defineProperty(p,'htmlText',{get:_hd.get,set:function(v){_hd.set.call(this,_rep(v));},configurable:true,enumerable:_hd.enumerable});}
        }
        if(!p.__cwTF){
            var _tfd=Object.getOwnPropertyDescriptor(p,'textFlow');
            if(_tfd&&_tfd.set){
                p.__cwTF=true;
                Object.defineProperty(p,'textFlow',{get:_tfd.get,set:function(v){
                    if(v&&v.length){
                        var vv=[];
                        for(var i=0;i<v.length;i++){
                            var item=v[i];
                            if(item&&typeof item.text==='string'){
                                vv.push({text:_rep(item.text),style:item.style});
                            } else { vv.push(item); }
                        }
                        _tfd.set.call(this,vv);
                    } else { _tfd.set.call(this,v); }
                },configurable:true,enumerable:_tfd.enumerable});
            }
        }
    }
    if(typeof eui!=='undefined'&&eui.Label&&eui.Label.prototype){
        var lp=eui.Label.prototype;
        if(!lp.__cwL){
            var _ld=Object.getOwnPropertyDescriptor(lp,'text');
            if(_ld&&_ld.set){lp.__cwL=true;Object.defineProperty(lp,'text',{get:_ld.get,set:function(v){_ld.set.call(this,_rep(v));},configurable:true,enumerable:_ld.enumerable});}
        }
        if(!lp.__cwLH){
            var _ldh=Object.getOwnPropertyDescriptor(lp,'htmlText');
            if(_ldh&&_ldh.set){lp.__cwLH=true;Object.defineProperty(lp,'htmlText',{get:_ldh.get,set:function(v){_ldh.set.call(this,_rep(v));},configurable:true,enumerable:_ldh.enumerable});}
        }
    }
    // Patch eui.Button.prototype.label so button labels are translated
    if(typeof eui!=='undefined'&&eui.Button&&eui.Button.prototype){
        var bp=eui.Button.prototype;
        if(!bp.__cwBL){
            var _bd=Object.getOwnPropertyDescriptor(bp,'label');
            if(_bd&&_bd.set){bp.__cwBL=true;Object.defineProperty(bp,'label',{get:_bd.get,set:function(v){_bd.set.call(this,_rep(v));},configurable:true,enumerable:_bd.enumerable});}
        }
    }
    // Patch ServerSelectView.configUI: guard against null serverList
    if(typeof ServerSelectView!=='undefined'&&!ServerSelectView.prototype.__cwSSV){
        ServerSelectView.prototype.__cwSSV=true;
        var _origCfgSSV=ServerSelectView.prototype.configUI;
        ServerSelectView.prototype.configUI=function(){
            if(this._parent&&!this._parent.serverList){
                this._parent.serverList=[{list:[{name:'Server 1',host:location.hostname,port:9002,serverID:10001,state:0}]}];
            }
            _origCfgSSV.call(this);
        };
    }
    // Patch LoginView.show() to pre-fetch server list so Switch Server button works
    if(typeof LoginView!=='undefined'&&!LoginView.prototype.__cwPDS){
        LoginView.prototype.__cwPDS=true;
        var _origShowLV=LoginView.prototype.show;
        LoginView.prototype.show=function(){
            _origShowLV.call(this);
            try{this.postDataToServer();}catch(ex){}
        };
    }
    // Patch LoginView.onClickHandler to require auth before socket.init()
    // _inputPassword and _lblError are in skinParts → bound directly to host instance
    // v90: do NOT call _origClick at all — the original handler only sets clientName +
    //      localStorage then calls socket.init(). We replicate those two lines manually
    //      so no async game-engine side-effects (timers, state flags) are set up before
    //      the XHR completes and we call the real socket.init().
    if(typeof LoginView!=='undefined'&&!LoginView.prototype.__cwAuth){
        LoginView.prototype.__cwAuth=true;
        var _origClick=LoginView.prototype.onClickHandler;
        LoginView.prototype.onClickHandler=function(e){
            if(e.currentTarget!==this._btnEnter){
                return _origClick.call(this,e);
            }
            var self=this;
            var username=this._inputClient?this._inputClient.text:'';
            var pwdField=this._inputPassword;
            var errLabel=this._lblError;
            var password=pwdField?pwdField.text:'';
            if(!username){
                if(errLabel)errLabel.text='Enter account name.';
                return;
            }
            if(!password||password.length<6){
                if(errLabel)errLabel.text='Password: min 6 characters.';
                return;
            }
            if(errLabel)errLabel.text='Verifying...';

            // Set model state directly (mirrors original handler's 2 pre-init lines)
            // without calling _origClick, so no engine state is set up prematurely.
            try{Manager.model.getLogin().clientName=username;}catch(_ex){}
            try{egret.localStorage.setItem('username',username);}catch(_ex){}

            // Async: verify credentials, then open socket on success.
            var xr=new XMLHttpRequest();
            xr.open('POST','auth.php',true);
            xr.timeout=8000;
            xr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');
            xr.onload=function(){
                try{
                    var res=JSON.parse(xr.responseText||xr.response);
                    if(res.ok){
                        if(errLabel)errLabel.text='';
                        try{
                            if(typeof window._cwSocketReady==='function')window._cwSocketReady();
                            else Manager.socket.init.call(Manager.socket);
                        }catch(_ex){}
                    }else{
                        if(errLabel)errLabel.text=res.error||'Login failed.';
                    }
                }catch(ex){
                    if(errLabel)errLabel.text='Server error.';
                }
            };
            xr.onerror=function(){
                if(errLabel)errLabel.text='Network error.';
            };
            xr.ontimeout=function(){
                if(errLabel)errLabel.text='Server timeout. Try again.';
            };
            xr.send('username='+encodeURIComponent(username)+'&password='+encodeURIComponent(password));
        };
    }
    // Patch ArenaMaxListItem.setCVO: called right after skin parts bind, _cvo set immediately
    if(typeof ArenaMaxListItem!=='undefined'&&ArenaMaxListItem.prototype.setCVO&&!ArenaMaxListItem.prototype.__cwAMLS){
        ArenaMaxListItem.prototype.__cwAMLS=true;
        var _origAMLS=ArenaMaxListItem.prototype.setCVO;
        ArenaMaxListItem.prototype.setCVO=function(t){
            _origAMLS.call(this,t);
            try{if(this._txt&&this._cvo&&this._cvo.rankTarget!=null)this._txt.text='Rank #'+this._cvo.rankTarget;}catch(ex){}
        };
    }
    // Patch ArenaMaxListItem.configUI: second pass to catch any later re-init
    if(typeof ArenaMaxListItem!=='undefined'&&ArenaMaxListItem.prototype.configUI&&!ArenaMaxListItem.prototype.__cwAMLCUI){
        ArenaMaxListItem.prototype.__cwAMLCUI=true;
        var _origAMLCUI=ArenaMaxListItem.prototype.configUI;
        ArenaMaxListItem.prototype.configUI=function(){
            _origAMLCUI.call(this);
            try{if(this._txt&&this._cvo&&this._cvo.rankTarget!=null)this._txt.text='Rank #'+this._cvo.rankTarget;}catch(ex){}
        };
    }
    // Patch GemView.configUI: resize Gemstone title image (+81w +25h from 181x52)
    if(typeof GemView!=='undefined'&&GemView.prototype&&!GemView.prototype.__cwGVT){
        GemView.prototype.__cwGVT=true;
        var _origGVCfg=GemView.prototype.configUI;
        GemView.prototype.configUI=function(){
            _origGVCfg.call(this);
            try{
                var ti=this._thisParent&&this._thisParent._titleImg;
                if(ti){ti.width=208;ti.height=60;ti.y=-8;}
            }catch(ex){}
        };
    }
    // Patch SceneRobotNameCVO.getRandomName: translate NPC robot names via _npcN lookup
    if(typeof SceneRobotNameCVO!=='undefined'&&SceneRobotNameCVO.getRandomName&&!SceneRobotNameCVO.__cwRN){
        SceneRobotNameCVO.__cwRN=true;
        var _origGRN=SceneRobotNameCVO.getRandomName;
        SceneRobotNameCVO.getRandomName=function(){var n=_origGRN.call(this);return _npcN[n]||n;};
    }
    // Also translate SceneRobotStyleCVO playerName
    if(typeof SceneRobotStyleCVO!=='undefined'&&SceneRobotStyleCVO.getCVO&&!SceneRobotStyleCVO.__cwRSN){
        SceneRobotStyleCVO.__cwRSN=true;
        var _origGetCVO=SceneRobotStyleCVO.getCVO;
        SceneRobotStyleCVO.getCVO=function(id){
            var cvo=_origGetCVO.call(this,id);
            if(cvo&&cvo.playerName&&_npcN[cvo.playerName])cvo.playerName=_npcN[cvo.playerName];
            return cvo;
        };
    }
    _fixAttrCVO();
    // Patch PetView2._attrTxt: reduce font size 24→22 so translated stat labels
    // ("Max HP+350600" etc.) don't wrap in the 180px container on PC browsers
    // where Microsoft YaHei falls back to a wider font.
    if(typeof PetView2!=='undefined'&&!PetView2.prototype.__cwPV2){
        PetView2.prototype.__cwPV2=true;
        var _origPV2Start=PetView2.prototype.start;
        PetView2.prototype.start=function(){
            _origPV2Start.call(this);
            try{if(this._attrTxt)this._attrTxt.size=22;}catch(e){}
        };
    }
    // Patch PetSkillView.configUI: increase bgHeight 370→440 to accommodate
    // 2-line description text after EXML _descTxt width constraint was added.
    if(typeof PetSkillView!=='undefined'&&!PetSkillView.prototype.__cwPSV){
        PetSkillView.prototype.__cwPSV=true;
        var _origPSVConfig=PetSkillView.prototype.configUI;
        PetSkillView.prototype.configUI=function(){
            _origPSVConfig.call(this);
            try{if(this._baseView)this._baseView.bgHeight=440;}catch(e){}
        };
    }
    _retranslate();
}
function _retranslate(){
    var s=(typeof egret!=='undefined')&&egret.stage;
    if(!s)return;
    function walk(d){
        if(!d)return;
        try{
            if(d.isFlow){
                var tf=d.textFlow;
                if(tf&&tf.length){
                    var needsRetrans=false;
                    for(var fi=0;fi<tf.length;fi++){
                        if(tf[fi]&&typeof tf[fi].text==='string'&&_rep(tf[fi].text)!==tf[fi].text){needsRetrans=true;break;}
                    }
                    if(needsRetrans)d.textFlow=tf;
                }
            } else {
                var t=d.text;
                if(typeof t==='string'&&t.length&&_rep(t)!==t)d.text=t;
            }
            var h=d.htmlText;
            if(typeof h==='string'&&h.length&&_rep(h)!==h)d.htmlText=h;
        }catch(e){}
        try{var n=d.numChildren;for(var i=0;i<n;i++)walk(d.getChildAt(i));}catch(e){}
    }
    walk(s);
}
document.title='EN v94';
_patch();
var _t=setInterval(function(){_patch();},500);
setTimeout(function(){
    clearInterval(_t);
    setInterval(function(){_retranslate();},3000);
},15000);
})();
